Import Libraries

In [38]:
import pandas as pd
import numpy as np
import os
import yfinance as yf

Currency Codes

In [39]:
country_currency_codes_table = {
    'Burundi': 'BIF',
    'Benin': 'XOF',
    'Burkina Faso': 'XOF',
    'Central African Republic': 'XAF',
    "Côte d'Ivoire": 'XOF',
    'Cameroon': 'XAF',
    'Democratic Republic of the Congo': 'CDF',
    'Republic of Congo': 'XAF',
    'Comoros': 'KMF',
    'Eritrea': 'ERN',
    'Ethiopia': 'ETB',
    'Ghana': 'GHS',
    'Guinea': 'GNF',
    'The Gambia': 'GMD',
    'Guinea-Bissau': 'XOF',
    'Liberia': 'LRD',
    'Madagascar': 'MGA',
    'Mali': 'XOF',
    'Mozambique': 'MZN',
    'Mauritania': 'MRU',
    'Malawi': 'MWK',
    'Niger': 'XOF',
    'Rwanda': 'RWF',
    'Sudan': 'SDG',
    'Senegal': 'XOF',
    'Sierra Leone': 'SLL',
    'Somalia': 'SOS',
    'Sao Tomee and Principe': 'STN',
    'Chad': 'XAF',
    'Togo': 'XOF',
    'Tanzania': 'TZS',
    'Uganda': 'UGX',
    'Zambia': 'ZMW'
}

Read Data

In [40]:
#read in stata dataset as dataframe "country_code_df"
country_code_df = pd.read_stata("codesffactors_Mar23_2019.dta") 
country_code_df.replace('--', np.nan, inplace=True) #replace all entries that are '--' with NaN data value

country_code_df.head()

,countryname,wbctry,wbcode,wbregion,wbigroup2017,wblcat2017,hipc,emu,cemac,waemu,imfcode,imfweocode,imfweoiso,imfweoctry,region
0,Aruba,Aruba,ABW,Latin America & Caribbean,High income,NaN,0,0,0,0,NaN,314.0,ABW,Aruba,LAC
1,Afghanistan,Afghanistan,AFG,South Asia,Low income,IDA,1,0,0,0,512.0,512.0,AFG,Afghanistan,SAS
2,Angola,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD,0,0,0,0,614.0,614.0,AGO,Angola,SSA
3,Anguilla,NaN,AIA,Latin America & Caribbean,NaN,NaN,0,0,0,0,312.0,NaN,NaN,NaN,LAC
4,Albania,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD,0,0,0,0,914.0,914.0,ALB,Albania,ECA

In [41]:
region_classification_ls = country_code_df['wbregion'].unique() #get a list of region classifications
income_classification_ls = country_code_df['wbigroup2017'].unique() #get a list of income classifications
income_classification_ls = [x for x in income_classification_ls if not pd.isna(x)] # remove '--' from income_classification_ls

print(f"The region classifications are: {', '.join(country for country in region_classification_ls)}")
print(f"The income classifications are: {', '.join(country for country in income_classification_ls)}")

The region classifications are: Latin America & Caribbean, South Asia, Sub-Saharan Africa, Europe & Central Asia, Middle East & North Africa, East Asia & Pacific, North America
The income classifications are: High income, Low income, Lower middle income, Upper middle income

In [42]:
ssa_hipc_countries = country_code_df[(country_code_df['hipc'] == 1) & (country_code_df['wbregion'] == 'Sub-Saharan Africa')]
ssa_hipc_countries_ls = ssa_hipc_countries['imfweoctry'].to_list()

ssa_hipc_countries_ls

['Burundi',
 'Benin',
 'Burkina Faso',
 'Central African Republic',
 "Côte d'Ivoire",
 'Cameroon',
 'Democratic Republic of the Congo',
 'Republic of Congo',
 'Comoros',
 'Eritrea',
 'Ethiopia',
 'Ghana',
 'Guinea',
 'The Gambia',
 'Guinea-Bissau',
 'Liberia',
 'Madagascar',
 'Mali',
 'Mozambique',
 'Mauritania',
 'Malawi',
 'Niger',
 'Rwanda',
 'Sudan',
 'Senegal',
 'Sierra Leone',
 'Somalia',
 'São Tomé and Príncipe',
 'Chad',
 'Togo',
 'Tanzania',
 'Uganda',
 'Zambia']

Read in IMF's Government Finance Statistics

In [43]:
master_table = {}
folder_path = "expenditure-investment-data"

# Loop that goes through all files 'file_name' in the folder 'folder_path'
for file_name in os.listdir(folder_path):
  if file_name.endswith('.xlsx') and not file_name.startswith('~$'): #check to see if is spreadsheet .xlsx format
    raw_df = pd.read_excel(folder_path+ "/" + file_name) #read in .xlsx as dataframe
    master_table[file_name[:-5]] = raw_df #store dataframe as an entry in the master_table hash table

# master_table["Central African Republic"]
for key in master_table:
  print(master_table[key])

                                           Unnamed: 0   Unnamed: 1  \
0   Statement of Operations (Revenue, Expenditures...          NaN
1                                      Country: Benin          NaN
2                Sector: Budgetary central government          NaN
3                             Unit: Domestic currency          NaN
4                                     Scale: Billions          NaN
5                                                 NaN          NaN
6                                                 NaN  2010.000000
7                    TRANSACTIONS AFFECTING NET WORTH          NaN
8                                             Revenue   648.375468
9                                               Taxes   536.250675
10                               Social contributions    16.366616
11                                             Grants    52.312694
12                                      Other revenue    43.445484
13                                            Expense   459.011490
14                          Compensation of employees   235.600075
15                          Use of goods and services    71.197566
16                       Consumption of fixed capital          NaN
17                                           Interest    17.734935
18                                          Subsidies    20.525565
19                                             Grants   101.794146
20                                    Social benefits     0.775000
21                                      Other expense    11.384204
22                            Gross operating balance   189.363978
23                              Net operating balance          NaN
24                TRANSACTIONS IN NONFINANCIAL ASSETS          NaN
25        Net/gross investment in nonfinancial assets   122.284733
26                                        Expenditure   581.296223
27                Net lending (+) / Net borrowing (-)    67.079246
28                    Primary net lending / borrowing    84.814180
29  TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITI...          NaN
30                Net acquisition of financial assets    22.436895
31                      Net incurrence of liabilities    90.192172

     Unnamed: 2   Unnamed: 3  Unnamed: 4
0           NaN          NaN         NaN
1           NaN          NaN         NaN
2           NaN          NaN         NaN
3           NaN          NaN         NaN
4           NaN          NaN         NaN
5           NaN          NaN         NaN
6   2011.000000  2012.000000      2013.0
7           NaN          NaN         NaN
8    676.747224   701.455221       803.0
9    546.563646   599.904265       696.0
10    18.602945    20.718088        22.8
11    80.536882    46.590103        45.9
12    31.043751    34.242765        38.4
13   457.660567   534.669798       577.5
14   242.117067   267.900275       296.2
15    68.703453    94.436470       106.1
16          NaN          NaN         NaN
17    14.973871    23.143175        19.9
18    33.553247    55.091217        49.5
19    86.975987    80.503177        91.1
20     0.987000     0.783000         0.9
21    10.349942    12.812484        13.7
22   219.086657   166.785423       225.5
23          NaN          NaN         NaN
24          NaN          NaN         NaN
25   124.860777   101.180504       102.3
26   582.521345   635.850302       679.8
27    94.225880    65.604919       123.2
28   109.199751    88.748094       143.1
29          NaN          NaN         NaN
30    -0.905666   -16.747880        -5.7
31   133.506866    80.828197       161.0
                                           Unnamed: 0   Unnamed: 1  \
0   Statement of Operations (Revenue, Expenditures...          NaN
1                                    Country: Senegal          NaN
2                Sector: Budgetary central government          NaN
3                             Unit: Domestic currency          NaN
4                                     Scale: Billions          NaN
5                                                 NaN          NaN
6                                                 NaN  2010.000000
7                    TRANSACTIONS AFFECTING NET WORTH          NaN
8                                             Revenue  1398.343124
9                                               Taxes  1194.723625
10                               Social contributions     0.000000
11                                             Grants   161.871000
12                                      Other revenue    41.748499
13                                            Expense   995.128703
14                          Compensation of employees   392.309713
15                          Use of goods and services   300.438982
16                       Consumption of fixed capital          NaN
17                                           Interest    60.080007
18                                          Subsidies          NaN
19                                             Grants          NaN
20                                    Social benefits          NaN
21                                      Other expense          NaN
22                            Gross operating balance   403.214421
23                              Net operating balance          NaN
24                TRANSACTIONS IN NONFINANCIAL ASSETS          NaN
25        Net/gross investment in nonfinancial assets   735.636661
26                                        Expenditure  1730.765364
27                Net lending (+) / Net borrowing (-)  -332.422240
28                    Primary net lending / borrowing  -272.342233
29  TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITI...          NaN
30                Net acquisition of financial assets   -75.768400
31                      Net incurrence of liabilities   266.970163

    Unnamed: 2  Unnamed: 3  Unnamed: 4   Unnamed: 5   Unnamed: 6   Unnamed: 7  \
0          NaN         NaN         NaN          NaN          NaN          NaN
1          NaN         NaN         NaN          NaN          NaN          NaN
2          NaN         NaN         NaN          NaN          NaN          NaN
3          NaN         NaN         NaN          NaN          NaN          NaN
4          NaN         NaN         NaN          NaN          NaN          NaN
5          NaN         NaN         NaN          NaN          NaN          NaN
6       2011.0      2012.0     2013.00  2014.000000  2015.000000  2016.000000
7          NaN         NaN         NaN          NaN          NaN          NaN
8       1525.6      1652.9     1658.98  1935.462270  2093.436385  2248.172342
9       1286.9      1375.5         NaN  1482.525348  1664.093595  1854.824668
10         0.0         0.0        0.00     0.000000     0.000000     0.000000
11       150.0       205.9      187.54   311.786870   232.016910   112.248000
12        88.7        71.5         NaN   141.150052   197.325880   281.099673
13      1192.5      1218.6     1262.78  1775.813946  1956.087661  2236.479601
14       428.0       461.8      464.70   489.976354   526.124040   572.316884
15       342.2         NaN      313.64   360.707701   384.285499   321.139056
16         NaN         NaN         NaN          NaN          NaN          NaN
17       102.7       107.3      113.20   138.961335   159.754852   187.650263
18         NaN         NaN         NaN    12.392875    50.620927    52.295928
19         NaN         NaN         NaN   570.157550   667.324314   877.258143
20         NaN         NaN         NaN    30.136732    60.227518     6.194220
21         NaN         NaN         NaN   173.481399   107.750510   219.625108
22       333.1       434.3      396.20   159.648324   137.348724    11.692741
23         NaN         NaN         NaN          NaN          NaN          NaN
24         NaN         NaN         NaN          NaN          NaN          NaN
25       752.4       814.4      801.30   492.093431   524.298114   254.009158
26      1944.9      2033.0     2064.08  2267.907377  2480.385776  2490.488759
27      -419.3      -380.1     -405.10  -332.445107  -386.949391  -242.316417
28      -316.6      -272.8     -291.90  -193.483772  -227.194538   -54.666155
29         NaN         NaN         NaN          NaN          NaN          NaN
30       207.4       147.7         NaN   122.154560   -92.579667   185.402616
31       624.3       435.3         NaN   455.020433   298.909283   443.818566

     Unnamed: 8   Unnamed: 9  Unnamed: 10
0           NaN          NaN          NaN
1           NaN          NaN          NaN
2           NaN          NaN          NaN
3           NaN          NaN          NaN
4           NaN          NaN          NaN
5           NaN          NaN          NaN
6   2017.000000  2018.000000  2019.000000
7           NaN          NaN          NaN
8   2471.343407  2538.046788  2904.590889
9   1939.282137  2102.982357  2525.773555
10     0.000000     0.000000     0.000000
11   264.829543   256.444430   224.326020
12   267.231728   178.623834   154.491314
13  2315.833361  2429.435896  2755.023316
14   599.956716   682.013116   733.266929
15   302.830536   418.588117   593.539584
16          NaN          NaN          NaN
17   233.888593   263.157069   271.182106
18    42.527275   130.166617   212.088602
19   740.828748   650.830354   640.964939
20     6.982280     7.106059    15.392737
21   388.819213   277.574564   288.588419
22   155.510046   108.610892   149.567574
23          NaN          NaN          NaN
24          NaN          NaN          NaN
25   488.848618   587.697793   679.075043
26  2804.681979  3017.133688  3434.098358
27  -333.338572  -479.086901  -529.507469
28   -99.449979  -215.929831  -258.325363
29          NaN          NaN          NaN
30   194.861238   432.313343   277.462668
31   551.290968   910.138558   816.298397
                                           Unnamed: 0  Unnamed: 1  Unnamed: 2  \
0   Statement of Operations (Revenue, Expenditures...         NaN         NaN
1                              Country: Côte d'Ivoire         NaN         NaN
2                Sector: Budgetary central government         NaN         NaN
3                             Unit: Domestic currency         NaN         NaN
4                                     Scale: Billions         NaN         NaN
5                                                 NaN         NaN         NaN
6                                                 NaN    2010.000    2011.000
7                    TRANSACTIONS AFFECTING NET WORTH         NaN         NaN
8                                             Revenue    2099.360    1530.420
9                                               Taxes    1765.580    1309.250
10                               Social contributions       0.000       0.000
11                                             Grants     152.811      32.861
12                                      Other revenue     180.966     188.315
13                                            Expense    1836.710    1661.720
14                          Compensation of employees     800.475     719.800
15                          Use of goods and services     371.431     299.219
16                       Consumption of fixed capital         NaN         NaN
17                                           Interest     194.330     219.250
18                                          Subsidies     169.691     179.642
19                                             Grants      25.042      66.350
20                                    Social benefits       0.000       0.000
21                                      Other expense     275.738     177.460
22                            Gross operating balance     262.650    -131.300
23                              Net operating balance         NaN         NaN
24                TRANSACTIONS IN NONFINANCIAL ASSETS         NaN         NaN
25        Net/gross investment in nonfinancial assets     342.574     281.829
26                                        Expenditure    2179.284    1943.549
27                Net lending (+) / Net borrowing (-)     -79.924    -413.129
28                    Primary net lending / borrowing     114.406    -193.879
29  TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITI...         NaN         NaN
30                Net acquisition of financial assets     136.324     181.877
31                      Net incurrence of liabilities     295.964     699.175

     Unnamed: 3  Unnamed: 4   Unnamed: 5   Unnamed: 6   Unnamed: 7  \
0           NaN         NaN          NaN          NaN          NaN
1           NaN         NaN          NaN          NaN          NaN
2           NaN         NaN          NaN          NaN          NaN
3           NaN         NaN          NaN          NaN          NaN
4           NaN         NaN          NaN          NaN          NaN
5           NaN         NaN          NaN          NaN          NaN
6   2012.000000    2013.000  2014.000000  2015.000000  2016.000000
7           NaN         NaN          NaN          NaN          NaN
8   2325.910000    2675.160  2881.440262  3577.017161  3657.722804
9   1968.230000    2246.230  2439.937728  3027.100001  3287.603482
10     0.000000       0.000     0.000000     0.000000     0.000000
11    81.208000     201.460   314.388534   282.199911   292.418000
12   276.470000     227.467   127.114000   267.717249    77.701322
13  2098.380000    2097.270  2222.664104  3644.359955  3844.074727
14   934.674000    1038.900  1183.300000  1217.083000  1279.169000
15   388.571000     376.977   474.961004   617.481812   652.495298
16          NaN         NaN          NaN          NaN          NaN
17   232.921000     214.779   138.501000   297.665000   360.135000
18   232.175000     164.068   127.997500   576.825016   417.245292
19    84.328435      83.850    93.869000   729.526430   871.591465
20     0.000000       0.000     0.000000    87.140541    66.702736
21   225.714000     218.689   204.035600   118.638157   196.735936
22   227.530000     577.890   658.776158   -67.342794  -186.351923
23          NaN         NaN          NaN          NaN          NaN
24          NaN         NaN          NaN          NaN          NaN
25   612.240000     927.215   983.800000   589.992517   744.659975
26  2710.620000    3024.485  3206.464104  4234.352472  4588.734702
27  -384.710000    -349.325  -325.023842  -657.335311  -931.011898
28  -151.789000    -134.546  -186.522842  -359.670311  -570.876898
29          NaN         NaN          NaN          NaN          NaN
30   -48.286071     195.353   159.884935   224.983000  -110.832972
31   244.597000     550.296   686.245000   868.000000   814.133000

     Unnamed: 8   Unnamed: 9  Unnamed: 10
0           NaN          NaN          NaN
1           NaN          NaN          NaN
2           NaN          NaN          NaN
3           NaN          NaN          NaN
4           NaN          NaN          NaN
5           NaN          NaN          NaN
6   2017.000000  2018.000000  2019.000000
7           NaN          NaN          NaN
8   3911.226661  4136.075345  4507.253615
9   3584.711052  3792.159618  4127.136003
10     0.000000     0.000000     0.000000
11   266.100000   246.180000   274.912140
12    60.415609    97.735727   105.205471
13  4557.649286  4790.437981  4821.135180
14  1382.379041  1483.784688  1560.900000
15   741.806234   626.273597   572.539383
16          NaN          NaN          NaN
17   379.459243   434.160000   520.934848
18   552.724514   583.234903   473.440213
19   959.761848  1169.588382  1241.607081
20    67.069104    93.942987    89.894353
21   474.449302   399.453424   361.819302
22  -646.422625  -654.362636  -313.881565
23          NaN          NaN          NaN
24          NaN          NaN          NaN
25   415.625142   421.626916   607.711989
26  4973.274428  5212.064897  5428.847169
27 -1062.047767 -1075.989551  -921.593554
28  -682.588524  -641.829551  -400.658707
29          NaN          NaN          NaN
30   263.984036    74.327671   161.404668
31  1323.419554  1158.277215  1092.925530
                                           Unnamed: 0   Unnamed: 1  \
0   Statement of Operations (Revenue, Expenditures...          NaN
1                               Country: Burkina Faso          NaN
2                Sector: Budgetary central government          NaN
3                             Unit: Domestic currency          NaN
4                                     Scale: Billions          NaN
5                                                 NaN          NaN
6                                                 NaN  2010.000000
7                    TRANSACTIONS AFFECTING NET WORTH          NaN
8                                             Revenue   880.219000
9                                               Taxes   565.750000
10                               Social contributions     0.000000
11                                             Grants   198.940000
12                                      Other revenue   115.529000
13                                            Expense   529.961000
14                          Compensation of employees   245.820000
15                          Use of goods and services    90.764421
16                       Consumption of fixed capital          NaN
17                                           Interest    21.354240
18                                          Subsidies    18.083948
19                                             Grants    44.653921
20                                    Social benefits     0.000000
21                                      Other expense   109.285000
22                            Gross operating balance   350.258000
23                              Net operating balance          NaN
24                TRANSACTIONS IN NONFINANCIAL ASSETS          NaN
25        Net/gross investment in nonfinancial assets   552.353000
26                                        Expenditure  1082.314000
27                Net lending (+) / Net borrowing (-)  -202.095000
28                    Primary net lending / borrowing  -180.740760
29  TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITI...          NaN
30                Net acquisition of financial assets    16.512677
31                      Net incurrence of liabilities   219.518000

     Unnamed: 2   Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6  \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3           NaN          NaN          NaN          NaN          NaN
4           NaN          NaN          NaN          NaN          NaN
5           NaN          NaN          NaN          NaN          NaN
6   2011.000000  2012.000000  2013.000000  2014.000000  2015.000000
7           NaN          NaN          NaN          NaN          NaN
8   1047.290000  1276.310000  1441.630000  1321.138714  1277.686312
9    695.634000   890.778000   992.610000   940.681613   928.991341
10     0.000000     0.000000     0.000000     0.000000     0.000000
11   253.670000   277.501000   324.364000   256.446823   230.041490
12    97.981964   108.036000   124.661000   124.010279   118.653481
13   628.254000   828.666000   818.972000   886.632195   923.205710
14   281.386000   332.340000   355.524000   437.287417   468.529629
15    97.144429   120.571000   118.596000   102.374172   109.443139
16          NaN          NaN          NaN          NaN          NaN
17    28.291579    41.805615    34.755278    44.011188    43.752145
18    31.684894    13.224867    11.042435    23.630863    11.865141
19    36.711105    61.099995    57.292069    89.473393    87.920063
20     0.000000     0.000000     0.000000     0.000000     0.000000
21   153.036000   259.625000   241.762000   189.855163   201.695594
22   419.036000   447.644000   622.658000   434.506520   354.480601
23          NaN          NaN          NaN          NaN          NaN
24          NaN          NaN          NaN          NaN          NaN
25   535.133000   625.077000   858.442000   554.129085   500.951627

Filtering

In [44]:
#REMOVE "JUNK" ROWS AND CONVERT TO CORRECT SCALE (MILLION/BILLIONS)
for key in master_table: #loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
  scale = master_table[key].iloc[4,0] #get if values have scale of billions or millions
  
  # Drop rows 0 to 5, reformatting indexes and column headers
  master_table[key] = master_table[key].drop([0, 1, 2, 3, 4, 5, 11]) 
  master_table[key] = master_table[key].reset_index(drop=True) 
  master_table[key].columns = master_table[key].iloc[0]
  master_table[key] = master_table[key][1:]
  master_table[key] = master_table[key].set_index(master_table[key].columns[0])
  master_table[key].columns = [int(float(col)) for col in master_table[key].columns]
  # master_table[key] = master_table[key].rename({4: 'Tax Grants'}, axis='index')
  # index_to_rename = master_table[key].index[master_table[key]['name'] == 'grants'][0]
  # master_table[key].at[index_to_rename, 'name'] = 'tax grants'


  # master_table[key] = master_table[key].fillna(0)

  if scale == "Scale: Billions":
    master_table[key] = master_table[key]* (10 ** 9) #multiple every value in dataframe by 1e9 if scale is billion
  elif scale == "Scale: Millions":
    master_table[key] = master_table[key]* (10 ** 6) #multiple every value in dataframe by 1e9 if scale is billion


#FILTER OUT YEAR COLUMNS ACCOUNTING DOESNT ADD UP
#first level: make sure 'Taxes', 'Social Contributions', 'Grants, 'Other Revenue' Sums to 'Revenue'
#second level: make sure 'Taxes on income, profits, & capital gains', 'Taxes on payroll & workforce', 'Taxes on property', 'Taxes on goods & services', 'Taxes on int trade & transactions', 'Other taxes n.e.c.' sum to 'Taxes'
first_level_ls = ['Compensation of employees', 'Use of goods and services', 'Consumption of fixed capital', 'Interest', 'Subsidies', 'Grants', 'Social benefits', 'Other expense', 'Net/gross investment in nonfinancial assets']
# second_level_ls = ['Taxes on income, profits, & capital gains', 'Taxes on payroll & workforce', 'Taxes on property', 'Taxes on goods & services', 'Taxes on int trade & transactions', 'Other taxes n.e.c.']
                  
for key in master_table:
  years_accounting_error_ls = []
  years_available = master_table[key].columns
  for year in years_available:
    country_year_df = master_table[key][year]
    # revenue = 0 
    exp = 0
    for category in first_level_ls:
      if category in country_year_df.index:
        exp += country_year_df[category]
      # else: 
      #   print(category)
    # for category in second_level_ls:
    #   if category in country_year_df.index:
    #     taxes += country_year_df[category]
    # if round(taxes, 0) != round(country_year_df['Taxes'], 0) or round(revenue, 0) != round(country_year_df['Revenue'], 0):
    
    margin = 0.001
    lower_bound_exp = country_year_df['Expenditure'] - country_year_df['Expenditure']*margin
    upper_bound_exp = country_year_df['Expenditure'] + country_year_df['Expenditure']*margin

    # print(lower_bound_exp)
    # print(upper_bound_exp)
    # print(exp)
    if exp < lower_bound_exp or exp > upper_bound_exp:
    
      print(f"{round(exp, 0)}, {round(country_year_df['exp'], 0)}")

      years_accounting_error_ls.append(year)
  
  print(key)
  print(years_accounting_error_ls)
  master_table[key].drop(columns=years_accounting_error_ls, inplace=True)
 
    
    

#FILTER OUT COUNTRIES WITH LESS THAN 7 YEARS OF DATA
less_than_seven_years_data_countries = [] #create list to store countries with less than 7 years of historial data
for key in master_table: #iterate through master_table
  num_columns = master_table[key].shape[1] #count the number of columns (each column represents a year)
  if num_columns < 7: #if less than 7 columns/year, add to list to delete
    less_than_seven_years_data_countries.append(key)

print('remove')
for country in less_than_seven_years_data_countries:
  print(country)
  del master_table[country] #delete countries with less than 7 years from data table

master_table["Zambia"]

Benin
[]
Senegal
[]
Côte d'Ivoire
[]
Burkina Faso
[]
Central African Republic
[]
Ghana
[]
Somalia
[]
Tanzania
[]
Zambia
[]
Democratic Republic of the Congo
[]
Rwanda
[]
Republic of Congo
[]
Sudan
[]
The Gambia
[]
Togo
[]
Mali
[]
Malawi
[]
Sao Tomee and Principe
[]
Mozambique
[]
Sierra Leone
[]
Guinea-Bissau
[]
Ethiopia
[]
Burundi
[]
Liberia
[]
Cameroon
[]
Madagascar
[]
Uganda
[]
remove
Benin
Somalia
The Gambia
Guinea-Bissau
Liberia

,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019
nan,,,,,,,,,,
TRANSACTIONS AFFECTING NET WORTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Revenue,1.612499e+10,2.401304e+10,2.403718e+10,2.678465e+10,3.128051e+10,3.641924e+10,4.283610e+10,4.870935e+10,5.619082e+10,6.231981e+10
Taxes,1.247751e+10,1.678054e+10,1.954949e+10,2.171162e+10,2.632927e+10,2.639580e+10,2.885596e+10,3.739301e+10,4.564338e+10,5.010771e+10
Social contributions,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Other revenue,1.485211e+09,3.138591e+09,2.331028e+09,2.858794e+09,3.301976e+09,7.155174e+09,1.032787e+10,4.103434e+09,7.770645e+09,8.768542e+09
Expense,1.426046e+10,1.652937e+10,2.170219e+10,2.701759e+10,3.383866e+10,4.260635e+10,4.842472e+10,5.152103e+10,5.533955e+10,6.596701e+10
Compensation of employees,6.394299e+09,6.950181e+09,1.066433e+10,1.137620e+10,1.536678e+10,1.639741e+10,1.864327e+10,2.002802e+10,2.096917e+10,2.233316e+10
Use of goods and services,3.440688e+09,6.507450e+09,5.394747e+09,7.762790e+09,7.342421e+09,8.956639e+09,1.425967e+10,1.244033e+10,8.807746e+09,9.273553e+09
Consumption of fixed capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Interest,1.530586e+09,1.063940e+09,1.829960e+09,2.415660e+09,4.834111e+09,7.197004e+09,1.064041e+10,1.176325e+10,1.865945e+10,2.770358e+10
Subsidies,1.173527e+08,2.089035e+07,2.425292e+08,1.670657e+09,0.000000e+00,0.000000e+00,0.000000e+00,3.565444e+06,0.000000e+00,0.000000e+00
Grants,2.567896e+09,1.602524e+09,3.050309e+09,3.461648e+09,6.014818e+09,9.712856e+09,4.616615e+09,6.541785e+09,6.247067e+09,6.298974e+09
Social benefits,5.247904e+07,1.586489e+08,2.225319e+08,1.300602e+08,1.556392e+08,7.960849e+07,1.170335e+08,5.408732e+08,3.313176e+08,1.760153e+08
Other expense,1.571635e+08,2.257381e+08,2.977767e+08,2.005753e+08,1.248869e+08,2.628338e+08,1.477188e+08,2.032016e+08,3.247996e+08,1.817299e+08
Gross operating balance,1.864532e+09,7.483670e+09,2.334988e+09,-2.329321e+08,-2.558150e+09,-6.187108e+09,-5.588613e+09,-2.811676e+09,8.512636e+08,-3.647205e+09
Net operating balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSACTIONS IN NONFINANCIAL ASSETS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Net/gross investment in nonfinancial assets,2.959842e+09,8.631882e+09,2.025303e+09,6.442498e+09,6.893751e+09,8.535520e+09,6.649908e+09,1.018697e+10,2.500954e+10,2.001023e+10
Expenditure,1.722030e+10,2.516125e+10,2.372749e+10,3.346008e+10,4.073241e+10,5.114187e+10,5.507462e+10,6.170800e+10,8.034909e+10,8.597725e+10
Net lending (+) / Net borrowing (-),-1.095310e+09,-1.148212e+09,3.096852e+08,-6.675430e+09,-9.451901e+09,-1.472263e+10,-1.223852e+10,-1.299864e+10,-2.415828e+10,-2.365744e+10
Primary net lending / borrowing,4.352757e+08,-8.427186e+07,2.139646e+09,-4.259770e+09,-4.617789e+09,-7.525624e+09,-1.598115e+09,-1.235390e+09,-5.498826e+09,4.046144e+09
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Net acquisition of financial assets,1.060380e+09,1.679854e+09,4.124685e+09,-4.909064e+08,1.944076e+09,7.831108e+09,-6.314038e+07,-1.847641e+10,6.563955e+08,1.056251e+09
Net incurrence of liabilities,2.699091e+09,4.285031e+09,1.422055e+10,5.674061e+09,1.120537e+10,2.135828e+10,9.737137e+09,2.713575e+10,1.723807e+10,2.175544e+10

Convert Currency

In [45]:
# print('keep')
# for key in master_table:
#   print(key)

# #CONVERT LOCAL CURRENCY DENOMINATED VALUES TO USD
# error_countries = []
# for key in master_table:
#   #get annual 2010-2019 USD to domestic currency exchange rate using yfinance library
#   currency = country_currency_codes_table[key] #retrieve currency symbol from 'country_currency_codes_table'
#   symbol = f"{currency}=X"
#   try:
#     data = yf.download(symbol, start="2010-01-01", end="2020-01-01", interval="1mo") #download monthly USD-Currency dataset from 2010-2020
#     yearly_data_df = data['Close'].resample('YE').mean() #get the annual average exchange rate outputted as datafram
#     yearly_data_table = yearly_data_df.to_dict() # Convert the yearly_data to a hash table with the date as the key
#     year_to_exchange_rate_dict = {key.year: value for key, value in yearly_data_table.items()} # Convert the keys to only the year part
#     print(year_to_exchange_rate_dict)

#     #convert DataFrame values to USD
#     for year in master_table[key].columns: #loop through columns in dataframe
#       year_int = int(year)  # Convert year to integer to match the dictionary keys
#       master_table[key][year] = master_table[key][year] / year_to_exchange_rate_dict[year_int] #divide each column's values by that year's exchange rate

#   except Exception as e: #if errored out
#     print(f"Could not fetch rate for {key} ({currency}): {e}")
#     error_countries.append(key) #add country to error list
#     pass
    
# for country in error_countries:
#   del master_table[country] #delete countries where currency conversion failed
 
# for key in master_table:
#   print(key)
#   print(master_table[key])

Calculate Percentages

In [46]:
# yearly_averages_percentage_ls = []

# year = 2010
# for year_average_df in yearly_averages_ls:


#   total_taxes = year_average_df['Expenditure']
#   year_average_percentage_df = year_average_df / total_taxes * 100 #take all values as a fraction of total expenditure, then convert decimal to percent, then round to two decimal places
  
#   first_level = 0
#   print(year)
#   for category in first_level_ls:
#     first_level += year_average_percentage_df[category]
#   print(first_level)
#   year += 1
  
#   yearly_averages_percentage_ls.append(year_average_percentage_df)

# for i in range(len(yearly_averages_percentage_ls)):
#   print(f"YEAR: {2010+i}")
#   print(yearly_averages_percentage_ls[i])


for key in master_table: #iterate through master_table
  total_taxes = master_table[key].loc['Expenditure']
  master_table[key] = master_table[key] / total_taxes * 100 #take all values as a fraction of total expenditure, then convert decimal to percent, then round to two decimal places

master_table['Central African Republic']

,2010,2011,2012,2014,2015,2016,2017,2018,2019
nan,,,,,,,,,
TRANSACTIONS AFFECTING NET WORTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Revenue,64.303163,64.641880,103.777902,113.745080,89.455507,104.461888,112.877803,102.120628,123.746810
Taxes,35.855305,44.657072,53.959563,24.400145,52.939240,45.812796,57.813503,52.397561,55.977026
Social contributions,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Other revenue,2.675500,5.400578,7.991041,2.874206,2.080739,3.315309,0.954819,1.080460,3.187153
Expense,69.667412,79.739346,54.039420,49.246634,90.417125,60.710637,70.840111,61.394608,66.884348
Compensation of employees,17.220627,23.707590,26.385051,34.224766,54.920374,30.603191,33.926042,30.153283,33.634773
Use of goods and services,40.341324,38.884420,12.876714,4.039469,14.761857,13.671939,18.823753,14.983236,18.805422
Consumption of fixed capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Interest,3.826075,3.599658,3.051907,1.380705,4.552323,0.719084,1.496049,1.377108,3.351482
Subsidies,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Grants,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Social benefits,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Other expense,0.160902,1.546451,NaN,9.601694,16.182571,15.716424,16.594267,14.880981,11.092671
Gross operating balance,-5.364249,-15.097466,49.738482,64.498446,-0.961617,43.751252,42.037692,40.726019,56.862462
Net operating balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSACTIONS IN NONFINANCIAL ASSETS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Net/gross investment in nonfinancial assets,30.332588,20.260654,45.960580,50.753366,9.582875,39.289363,29.159889,38.605392,33.115652
Expenditure,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Net lending (+) / Net borrowing (-),-35.696837,-35.358120,3.777902,13.745080,-10.544493,4.461888,12.877803,2.120628,23.746810
Primary net lending / borrowing,-31.870761,-31.758462,6.829809,15.125785,-5.992170,5.180972,14.373852,3.497735,27.098291
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Net acquisition of financial assets,NaN,NaN,NaN,13.967552,-6.791834,11.928522,11.212248,-3.278308,-1.015887
Net incurrence of liabilities,NaN,NaN,NaN,-1.295043,4.844563,7.199658,-1.607023,-1.860887,-23.558611

Calculate Yearly Averages

In [47]:
data_by_year_table = {
  2010: [],
  2011: [],
  2012: [],
  2013: [],
  2014: [],
  2015: [],
  2016: [],
  2017: [],
  2018: [],
  2019: [],
} #make table that stores data by year

# master_averages_ls = [] #make master averages list as place to store averages

for key in master_table:
  years_available = master_table[key].columns
  for year in data_by_year_table:
    if year in years_available:
      data_by_year_table[year].append(master_table[key][year])

yearly_averages_ls = [] #make a list of the yearly averages
for year in data_by_year_table:
  merged_year_df = pd.concat(data_by_year_table[year], axis=1, join='outer')
  #SUM OR MEAN?
  year_average_df = merged_year_df.mean(axis=1) #get the average of all the countries' averages
  yearly_averages_ls.append(year_average_df)

 
# #Get average over decade
# #loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
# for key in master_table:
#   per_category_average = master_table[key].mean(axis=1) #get the average of each category (ignoring np.NaN values) into a list
#   # per_category_average.drop('To other government units', inplace=True) #drop 'To other government units' since there's two rows named that and will error
#   master_averages_ls.append(per_category_average) #add each country average to to the master averages list



# merged_averages_df = pd.concat(master_averages_ls, axis=1, join='outer')
# average__of_averages_df = merged_averages_df.mean(axis=1) #get the average of all the countries' averages
# average__of_averages_df

for i in range(len(yearly_averages_ls)):
  print(f"YEAR: {2010+i}")
  print(yearly_averages_ls[i])

YEAR: 2010
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          97.267387
Taxes                                                            53.256718
Social contributions                                              0.392442
Other revenue                                                    16.112018
Expense                                                          66.667672
Compensation of employees                                        22.245489
Use of goods and services                                        17.154835
Consumption of fixed capital                                           NaN
Interest                                                          4.656631
Subsidies                                                         4.357664
Grants                                                           13.691973
Social benefits                                                   1.662801
Other expense                                                     3.453358
Gross operating balance                                          30.599715
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      33.332328
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                              -2.732613
Primary net lending / borrowing                                   1.924018
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                              13.627242
Net incurrence of liabilities                                    12.073924
dtype: float64
YEAR: 2011
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          90.605755
Taxes                                                            56.634222
Social contributions                                              0.476428
Other revenue                                                    13.026517
Expense                                                          66.588050
Compensation of employees                                        22.483094
Use of goods and services                                        17.903826
Consumption of fixed capital                                           NaN
Interest                                                          4.444010
Subsidies                                                         4.004717
Grants                                                           12.722352
Social benefits                                                   1.859675
Other expense                                                     3.021919
Gross operating balance                                          24.017704
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      33.411950
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                              -9.394245
Primary net lending / borrowing                                  -4.950235
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                              12.583342
Net incurrence of liabilities                                    20.288539
dtype: float64
YEAR: 2012
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          88.783694
Taxes                                                            60.679089
Social contributions                                              0.279929
Other revenue                                                    12.946080
Expense                                                          70.983336
Compensation of employees                                        25.874650
Use of goods and services                                        15.929715
Consumption of fixed capital                                           NaN
Interest                                                          4.741455
Subsidies                                                         2.630894
Grants                                                           14.434368
Social benefits                                                   1.730634
Other expense                                                     5.486580
Gross operating balance                                          17.800357
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      29.016664
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                             -11.216306
Primary net lending / borrowing                                  -6.474851
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               8.726568
Net incurrence of liabilities                                    22.588237
dtype: float64
YEAR: 2013
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          93.027576
Taxes                                                            59.936683
Social contributions                                              0.293437
Other revenue                                                    14.671925
Expense                                                          69.474131
Compensation of employees                                        25.744135
Use of goods and services                                        15.169608
Consumption of fixed capital                                           NaN
Interest                                                          4.713749
Subsidies                                                         3.182802
Grants                                                           14.749190
Social benefits                                                   1.386156
Other expense                                                     4.050469
Gross operating balance                                          23.553446
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      30.525869
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                              -6.972424
Primary net lending / borrowing                                  -2.258674
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               5.260855
Net incurrence of liabilities                                    14.348065
dtype: float64
YEAR: 2014
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          88.624423
Taxes                                                            59.357347
Social contributions                                              0.224947
Other revenue                                                    10.703230
Expense                                                          70.390264
Compensation of employees                                        25.498886
Use of goods and services                                        15.442669
Consumption of fixed capital                                           NaN
Interest                                                          5.483754
Subsidies                                                         1.924565
Grants                                                           15.209194
Social benefits                                                   1.484078
Other expense                                                     4.697304
Gross operating balance                                          18.234159
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      29.609736
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                             -11.375577
Primary net lending / borrowing                                  -5.891823
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               1.878892
Net incurrence of liabilities                                    16.583323
dtype: float64
YEAR: 2015
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          84.466679
Taxes                                                            61.845046
Social contributions                                              0.234352
Other revenue                                                     8.875901
Expense                                                          73.952652
Compensation of employees                                        26.721662
Use of goods and services                                        15.599450
Consumption of fixed capital                                           NaN
Interest                                                          6.085486
Subsidies                                                         2.269702
Grants                                                           16.835143
Social benefits                                                   1.619552
Other expense                                                     4.283585
Gross operating balance                                          10.514027
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      26.047348
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                             -15.533321
Primary net lending / borrowing                                  -9.447835
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               3.794374
Net incurrence of liabilities                                    21.414492
dtype: float64
YEAR: 2016
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          84.345729
Taxes                                                            62.768520
Social contributions                                              0.259415
Other revenue                                                     8.093652
Expense                                                          73.006578
Compensation of employees                                        26.573584
Use of goods and services                                        15.744850
Consumption of fixed capital                                           NaN
Interest                                                          6.804513
Subsidies                                                         2.463475
Grants                                                           15.402810
Social benefits                                                   1.759423
Other expense                                                     3.908222
Gross operating balance                                          11.339151
Net operating balance                                                  NaN
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      26.993422
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                             -15.654271
Primary net lending / borrowing                                  -8.849758
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               6.228715
Net incurrence of liabilities                                    22.067521
dtype: float64
YEAR: 2017
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          86.609633
Taxes                                                            64.597541
Social contributions                                              0.325430
Other revenue                                                     8.779571
Expense                                                          74.398352
Compensation of employees                                        26.653922
Use of goods and services                                        15.609159
Consumption of fixed capital                                      0.000000
Interest                                                          7.926530
Subsidies                                                         2.235365
Grants                                                           14.965976
Social benefits                                                   1.899725
Other expense                                                     5.154786
Gross operating balance                                          12.211281
Net operating balance                                             3.177363
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      25.601648
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                             -13.390367
Primary net lending / borrowing                                  -5.463837
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               2.558671
Net incurrence of liabilities                                    17.472677
dtype: float64
YEAR: 2018
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          87.848550
Taxes                                                            63.518505
Social contributions                                              0.457029
Other revenue                                                    12.389811
Expense                                                          75.559806
Compensation of employees                                        26.280837
Use of goods and services                                        15.823809
Consumption of fixed capital                                      0.000000
Interest                                                          8.999914
Subsidies                                                         3.140840
Grants                                                           14.287859
Social benefits                                                   1.944837
Other expense                                                     5.395795
Gross operating balance                                          12.288744
Net operating balance                                            36.829307
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      24.440194
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                             -12.151450
Primary net lending / borrowing                                  -3.151536
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               1.807872
Net incurrence of liabilities                                    13.695954
dtype: float64
YEAR: 2019
nan
TRANSACTIONS AFFECTING NET WORTH                                       NaN
Revenue                                                          90.618801
Taxes                                                            65.810108
Social contributions                                              0.301000
Other revenue                                                    11.861155
Expense                                                          75.509042
Compensation of employees                                        27.037598
Use of goods and services                                        15.069888
Consumption of fixed capital                                      0.000000
Interest                                                         10.051768
Subsidies                                                         3.858332
Grants                                                           13.377760
Social benefits                                                   2.060034
Other expense                                                     4.268014
Gross operating balance                                          15.109759
Net operating balance                                            42.369435
TRANSACTIONS IN NONFINANCIAL ASSETS                                    NaN
Net/gross investment in nonfinancial assets                      24.490958
Expenditure                                                     100.000000
Net lending (+) / Net borrowing (-)                              -9.381199
Primary net lending / borrowing                                   0.670569
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING)           NaN
Net acquisition of financial assets                               8.274614
Net incurrence of liabilities                                    17.996144
dtype: float64

Calculate Average Across Period

In [48]:
merged_percentages_df = pd.concat(yearly_averages_ls, axis=1, join='outer')
average_df = merged_percentages_df.mean(axis=1)
rounded_average_df = average_df.apply(lambda x: round(x, 2))

rounded_average_df = rounded_average_df.to_frame()
rounded_average_df

                                                         0
nan
TRANSACTIONS AFFECTING NET WORTH                       NaN
Revenue                                              89.22
Taxes                                                60.84
Social contributions                                  0.32
Other revenue                                        11.75
Expense                                              71.65
Compensation of employees                            25.51
Use of goods and services                            15.94
Consumption of fixed capital                          0.00
Interest                                              6.39
Subsidies                                             3.01
Grants                                               14.57
Social benefits                                       1.74
Other expense                                         4.37
Gross operating balance                              17.57
Net operating balance                                27.46
TRANSACTIONS IN NONFINANCIAL ASSETS                    NaN
Net/gross investment in nonfinancial assets          28.35
Expenditure                                         100.00
Net lending (+) / Net borrowing (-)                 -10.78
Primary net lending / borrowing                      -4.39
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIE...     NaN
Net acquisition of financial assets                   6.47
Net incurrence of liabilities                        17.85

In [49]:
#check
first_level = 0
for category in first_level_ls:
  first_level += average_df[category]
print(first_level)

# second_level = 0
# for category in second_level_ls:
#   second_level += average_df[category]
# print(second_level)

99.88115226306056

In [51]:
rounded_by_year_average_df = merged_percentages_df.round(2)
rounded_by_year_average_df

,0,1,2,3,4,5,6,7,8,9
nan,,,,,,,,,,
TRANSACTIONS AFFECTING NET WORTH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Revenue,97.27,90.61,88.78,93.03,88.62,84.47,84.35,86.61,87.85,90.62
Taxes,53.26,56.63,60.68,59.94,59.36,61.85,62.77,64.60,63.52,65.81
Social contributions,0.39,0.48,0.28,0.29,0.22,0.23,0.26,0.33,0.46,0.30
Other revenue,16.11,13.03,12.95,14.67,10.70,8.88,8.09,8.78,12.39,11.86
Expense,66.67,66.59,70.98,69.47,70.39,73.95,73.01,74.40,75.56,75.51
Compensation of employees,22.25,22.48,25.87,25.74,25.50,26.72,26.57,26.65,26.28,27.04
Use of goods and services,17.15,17.90,15.93,15.17,15.44,15.60,15.74,15.61,15.82,15.07
Consumption of fixed capital,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00
Interest,4.66,4.44,4.74,4.71,5.48,6.09,6.80,7.93,9.00,10.05
Subsidies,4.36,4.00,2.63,3.18,1.92,2.27,2.46,2.24,3.14,3.86
Grants,13.69,12.72,14.43,14.75,15.21,16.84,15.40,14.97,14.29,13.38
Social benefits,1.66,1.86,1.73,1.39,1.48,1.62,1.76,1.90,1.94,2.06
Other expense,3.45,3.02,5.49,4.05,4.70,4.28,3.91,5.15,5.40,4.27
Gross operating balance,30.60,24.02,17.80,23.55,18.23,10.51,11.34,12.21,12.29,15.11
Net operating balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.18,36.83,42.37
TRANSACTIONS IN NONFINANCIAL ASSETS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Net/gross investment in nonfinancial assets,33.33,33.41,29.02,30.53,29.61,26.05,26.99,25.60,24.44,24.49
Expenditure,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00
Net lending (+) / Net borrowing (-),-2.73,-9.39,-11.22,-6.97,-11.38,-15.53,-15.65,-13.39,-12.15,-9.38
Primary net lending / borrowing,1.92,-4.95,-6.47,-2.26,-5.89,-9.45,-8.85,-5.46,-3.15,0.67
TRANSACTIONS IN FINANCIAL ASSETS AND LIABILITIES (FINANCING),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Net acquisition of financial assets,13.63,12.58,8.73,5.26,1.88,3.79,6.23,2.56,1.81,8.27
Net incurrence of liabilities,12.07,20.29,22.59,14.35,16.58,21.41,22.07,17.47,13.70,18.00