Import Libraries

In [23]:
import pandas as pd
import numpy as np
import os
import yfinance as yf

Currency Codes

In [24]:
country_currency_codes_table = {
    'Burundi': 'BIF',
    'Benin': 'XOF',
    'Burkina Faso': 'XOF',
    'Central African Republic': 'XAF',
    "Côte d'Ivoire": 'XOF',
    'Cameroon': 'XAF',
    'Democratic Republic of the Congo': 'CDF',
    'Republic of Congo': 'XAF',
    'Comoros': 'KMF',
    'Eritrea': 'ERN',
    'Ethiopia': 'ETB',
    'Ghana': 'GHS',
    'Guinea': 'GNF',
    'The Gambia': 'GMD',
    'Guinea-Bissau': 'XOF',
    'Liberia': 'LRD',
    'Madagascar': 'MGA',
    'Mali': 'XOF',
    'Mozambique': 'MZN',
    'Mauritania': 'MRU',
    'Malawi': 'MWK',
    'Niger': 'XOF',
    'Rwanda': 'RWF',
    'Sudan': 'SDG',
    'Senegal': 'XOF',
    'Sierra Leone': 'SLL',
    'Somalia': 'SOS',
    'Sao Tomee and Principe': 'STN',
    'Chad': 'XAF',
    'Togo': 'XOF',
    'Tanzania': 'TZS',
    'Uganda': 'UGX',
    'Zambia': 'ZMW'
}

Read Data

In [25]:
#read in stata dataset as dataframe "country_code_df"
country_code_df = pd.read_stata("codesffactors_Mar23_2019.dta") 
country_code_df.replace('--', np.nan, inplace=True) #replace all entries that are '--' with NaN data value

country_code_df.head()

,countryname,wbctry,wbcode,wbregion,wbigroup2017,wblcat2017,hipc,emu,cemac,waemu,imfcode,imfweocode,imfweoiso,imfweoctry,region
0,Aruba,Aruba,ABW,Latin America & Caribbean,High income,NaN,0,0,0,0,NaN,314.0,ABW,Aruba,LAC
1,Afghanistan,Afghanistan,AFG,South Asia,Low income,IDA,1,0,0,0,512.0,512.0,AFG,Afghanistan,SAS
2,Angola,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD,0,0,0,0,614.0,614.0,AGO,Angola,SSA
3,Anguilla,NaN,AIA,Latin America & Caribbean,NaN,NaN,0,0,0,0,312.0,NaN,NaN,NaN,LAC
4,Albania,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD,0,0,0,0,914.0,914.0,ALB,Albania,ECA

In [26]:
region_classification_ls = country_code_df['wbregion'].unique() #get a list of region classifications
income_classification_ls = country_code_df['wbigroup2017'].unique() #get a list of income classifications
income_classification_ls = [x for x in income_classification_ls if not pd.isna(x)] # remove '--' from income_classification_ls

print(f"The region classifications are: {', '.join(country for country in region_classification_ls)}")
print(f"The income classifications are: {', '.join(country for country in income_classification_ls)}")

The region classifications are: Latin America & Caribbean, South Asia, Sub-Saharan Africa, Europe & Central Asia, Middle East & North Africa, East Asia & Pacific, North America
The income classifications are: High income, Low income, Lower middle income, Upper middle income

In [27]:
ssa_hipc_countries = country_code_df[(country_code_df['hipc'] == 1) & (country_code_df['wbregion'] == 'Sub-Saharan Africa')]
ssa_hipc_countries_ls = ssa_hipc_countries['imfweoctry'].to_list()

ssa_hipc_countries_ls

['Burundi',
 'Benin',
 'Burkina Faso',
 'Central African Republic',
 "Côte d'Ivoire",
 'Cameroon',
 'Democratic Republic of the Congo',
 'Republic of Congo',
 'Comoros',
 'Eritrea',
 'Ethiopia',
 'Ghana',
 'Guinea',
 'The Gambia',
 'Guinea-Bissau',
 'Liberia',
 'Madagascar',
 'Mali',
 'Mozambique',
 'Mauritania',
 'Malawi',
 'Niger',
 'Rwanda',
 'Sudan',
 'Senegal',
 'Sierra Leone',
 'Somalia',
 'São Tomé and Príncipe',
 'Chad',
 'Togo',
 'Tanzania',
 'Uganda',
 'Zambia']

Read in IMF's Government Finance Statistics

In [28]:
master_table = {}
folder_path = "revenue-data"

# Loop that goes through all files 'file_name' in the folder 'folder_path'
for file_name in os.listdir(folder_path):
  if file_name.endswith('.xlsx') and not file_name.startswith('~$'): #check to see if is spreadsheet .xlsx format
    raw_df = pd.read_excel(folder_path+ "/" + file_name) #read in .xlsx as dataframe
    master_table[file_name[:-5]] = raw_df #store dataframe as an entry in the master_table hash table

# master_table["Central African Republic"]
master_table["Benin"]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Detailed Revenue Breakdown,Detailed Revenue Breakdown,NaN,NaN,NaN
1,Country: Benin,NaN,NaN,NaN,NaN
2,Sector: Budgetary central government,NaN,NaN,NaN,NaN
3,Unit: Domestic currency,NaN,NaN,NaN,NaN
4,Scale: Billions,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,2010,2011.000000,2012.000000,2013.0
7,Revenue,648.375468,676.747224,701.455221,803.0
8,Taxes,536.250675,546.563646,599.904265,696.0
9,"Taxes on income, profits, & capital gains",104.846262,114.433242,118.073622,134.3
10,"Taxes on income, profits, & capital gains: ind...",46.00102,51.920867,56.326766,60.3
11,"Taxes on income, profits, & capital gains: cor...",47.753394,53.004216,53.119428,63.5
12,"Taxes on income, profits, & capital gains: other",11.091848,9.508159,8.627427,10.5
13,Taxes on payroll & workforce,5.104337,5.305594,5.726621,6.0
14,Taxes on property,1.681998,1.663647,1.280306,1.8
15,Taxes on goods & services,275.476543,282.885616,301.812744,349.9
16,General taxes on goods & services,232.742208,240.434099,269.594113,308.8
17,Excise taxes,23.150171,21.162270,8.915147,23.3
18,Taxes on int trade & transactions,142.732772,133.038373,163.913078,194.3
19,Other taxes n.e.c.,6.408763,9.237175,9.097894,9.7
20,Social contributions,16.366616,18.602945,20.718088,22.8
21,Social security contributions,16.366616,18.602945,20.718088,22.8
22,Other social contributions,0,0.000000,0.000000,0.0
23,Grants,52.312694,80.536882,46.590103,45.9
24,Grants from foreign govts,48.114343,76.823270,43.429216,40.9
25,Grants from int orgs,0,0.000000,0.000000,0.0
26,Grants from other gen govt,4.19835,3.713612,3.160887,5.0
27,Grants from other gen govt: current,4.19835,3.713612,3.160887,5.0
28,Grants from other gen govt: capital,0,0.000000,0.000000,0.0
29,Other revenue,43.445484,31.043751,34.242765,38.4
30,Property income,12.896126,10.423631,11.574620,9.0
31,Sales of goods & services,4.242073,4.135871,5.151810,8.0
32,"Fines, penalties & forfeits",1.156242,0.900713,0.878146,1.8
33,Other transfers,25.151043,15.583535,16.638189,NaN
34,"NI & SGS: premiums, fees & claims",0,0.000000,0.000000,NaN

Convert values to USD

In [29]:
#REMOVE "JUNK" ROWS AND CONVERT TO CORRECT SCALE (MILLION/BILLIONS)
for key in master_table: #loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
  scale = master_table[key].iloc[4,0] #get if values have scale of billions or millions
  
  # Drop rows 0 to 5, reformatting indexes and column headers
  master_table[key] = master_table[key].drop([0, 1, 2, 3, 4, 5]) 
  master_table[key] = master_table[key].reset_index(drop=True) 
  master_table[key].columns = master_table[key].iloc[0]
  master_table[key] = master_table[key][1:]
  master_table[key] = master_table[key].set_index(master_table[key].columns[0])
  master_table[key].columns = [int(float(col)) for col in master_table[key].columns]
  # master_table[key] = master_table[key].fillna(0)

  if scale == "Scale: Billions":
    master_table[key] = master_table[key]* (10 ** 9) #multiple every value in dataframe by 1e9 if scale is billion
  elif scale == "Scale: Millions":
    master_table[key] = master_table[key]* (10 ** 6) #multiple every value in dataframe by 1e9 if scale is billion


#FILTER OUT YEAR COLUMNS ACCOUNTING DOESNT ADD UP
#first level: make sure 'Taxes', 'Social Contributions', 'Grants, 'Other Revenue' Sums to 'Revenue'
#second level: make sure 'Taxes on income, profits, & capital gains', 'Taxes on payroll & workforce', 'Taxes on property', 'Taxes on goods & services', 'Taxes on int trade & transactions', 'Other taxes n.e.c.' sum to 'Taxes'
first_level_ls = ['Taxes', 'Social contributions', 'Grants', 'Other revenue']
second_level_ls = ['Taxes on income, profits, & capital gains', 'Taxes on payroll & workforce', 'Taxes on property', 'Taxes on goods & services', 'Taxes on int trade & transactions', 'Other taxes n.e.c.']
                  
for key in master_table:
  years_accounting_error_ls = []
  years_available = master_table[key].columns
  for year in years_available:
    country_year_df = master_table[key][year]
    revenue = 0 
    taxes = 0
    for category in first_level_ls:
      if category in country_year_df.index:
        revenue += country_year_df[category]
      # else: 
      #   print(category)
    for category in second_level_ls:
      if category in country_year_df.index:
        taxes += country_year_df[category]
    if round(taxes, 0) != round(country_year_df['Taxes'], 0) or round(revenue, 0) != round(country_year_df['Revenue'], 0):
      print(f"{round(taxes, 0)}, {round(country_year_df['Taxes'], 0)}, {round(revenue, 0)}, {round(country_year_df['Revenue'], 0)}")

      years_accounting_error_ls.append(year)
  
  print(key)
  print(years_accounting_error_ls)
  master_table[key].drop(columns=years_accounting_error_ls, inplace=True)
 




#FILTER OUT COUNTRIES WITH LESS THAN 7 YEARS OF DATA
less_than_seven_years_data_countries = [] #create list to store countries with less than 7 years of historial data
for key in master_table: #iterate through master_table
  num_columns = master_table[key].shape[1] #count the number of columns (each column represents a year)
  if num_columns < 7: #if less than 7 columns/year, add to list to delete
    less_than_seven_years_data_countries.append(key)

for country in less_than_seven_years_data_countries:
  del master_table[country] #delete countries with less than 7 years from data table



# #CONVERT LOCAL CURRENCY DENOMINATED VALUES TO USD
# error_countries = []
# for key in master_table:
#   #get annual 2010-2019 USD to domestic currency exchange rate using yfinance library
#   currency = country_currency_codes_table[key] #retrieve currency symbol from 'country_currency_codes_table'
#   symbol = f"{currency}=X"
#   try:
#     data = yf.download(symbol, start="2010-01-01", end="2020-01-01", interval="1mo") #download monthly USD-Currency dataset from 2010-2020
#     yearly_data_df = data['Close'].resample('YE').mean() #get the annual average exchange rate outputted as datafram
#     yearly_data_table = yearly_data_df.to_dict() # Convert the yearly_data to a hash table with the date as the key
#     year_to_exchange_rate_dict = {key.year: value for key, value in yearly_data_table.items()} # Convert the keys to only the year part
#     print(year_to_exchange_rate_dict)

#     #convert DataFrame values to USD
#     for year in master_table[key].columns: #loop through columns in dataframe
#       year_int = int(year)  # Convert year to integer to match the dictionary keys
#       master_table[key][year] = master_table[key][year] / year_to_exchange_rate_dict[year_int] #divide each column's values by that year's exchange rate

#   except Exception as e: #if errored out
#     print(f"Could not fetch rate for {key} ({currency}): {e}")
#     error_countries.append(key) #add country to error list
#     pass
    
# for country in error_countries:
#   del master_table[country] #delete countries where currency conversion failed
 
# master_table["Central African Republic"]

696000000000.0, 696000000000.0, 803100000000.0, 803000000000.0
Benin
[2013]
nan, nan, nan, 1658980000000.0
2102982357155.0, 2102982357155.0, 2538050621251.0, 2538046787551.0
Senegal
[2013, 2018]
1765582000000.0, 1765580000000.0, 2099357000000.0, 2099360000000.0
1309245000000.0, 1309250000000.0, 1530426000000.0, 1530420000000.0
1968232000000.0, 1968230000000.0, 2325908000000.0, 2325910000000.0
2246232795311.0, 2246230000000.0, 2675157000000.0, 2675160000000.0
Côte d'Ivoire
[2010, 2011, 2012, 2013]
565749183905.0, 565750000000.0, 880219000000.0, 880219000000.0
695634053206.0, 695634000000.0, 1047285963615.0, 1047290000000.0
890777678539.0, 890778000000.0, 1276315000000.0, 1276310000000.0
992608703991.0, 992610000000.0, 1441635000000.0, 1441630000000.0
Burkina Faso
[2010, 2011, 2012, 2013]
nan, 89135596491.0, nan, 159856425083.0
nan, 86631395622.0, nan, 125400435089.0
nan, 104734000000.0, nan, 201430000000.0
nan, 38344670841.0, 178749663179.0, 178749663179.0
nan, 54631151708.0, 92314460187.0, 92314460187.0
nan, 73625163568.0, 167879377909.0, 167879377909.0
nan, 85210311549.0, 166368619605.0, 166368619605.0
nan, 106583975699.0, 207727656493.0, 207727656493.0
Central African Republic
[2010, 2011, 2012, 2014, 2015, 2016, 2017, 2018]
Somalia
[]
Tanzania
[]
1631396700000.0, 1631400000000.0, 4034960000000.0, 4034950000000.0
Democratic Republic of the Congo
[2010]
505578227848.0, 505578000000.0, 982062667275.0, 982062000000.0
986837864155.0, 986838220030.0, 1501401313380.0, 1501401313380.0
1359411712673.0, 1359415316125.0, 2004371493732.0, 2004371493732.0
Rwanda
[2011, 2016, 2019]
449088332821.0, 449088000000.0, 3609988000000.0, 3609980000000.0
657435810389.0, 657460585915.0, 2979345676443.0, 2979345676443.0
Republic of Congo
[2010, 2012]
Sudan
[]
359871765296.0, 359872000000.0, 479559203769.0, 479559000000.0
450175108347.0, 498921783147.0, 604225591780.0, 604225591780.0
Togo
[2013, 2016]
768260000000.0, 768260000000.0, 1012104700000.0, 1012110000000.0
825255000000.0, 825255000000.0, 895797487620.0, 895797000000.0
852429000000.0, 852429000000.0, 1178598000000.0, 1178600000000.0
Mali
[2011, 2012, 2013]
161006170476.0, 161006000000.0, 256372097433.0, 256372000000.0
193572659753.0, 193573000000.0, 272176480439.0, 272176000000.0
203590569288.0, 203591000000.0, 257480157273.0, 257480000000.0
Malawi
[2010, 2011, 2012]
703733836.0, 703734000.0, 1612067828.0, 1612070000.0
Sao Tomee and Principe
[2012]
111522930604.0, 111523000000.0, 154285400847.0, 154285000000.0
Mozambique
[2013]
931291000000.0, 931291000000.0, 1551581000000.0, 1551580000000.0
1191235000000.0, 1191240000000.0, 2170763000000.0, 2170760000000.0
1571221000000.0, 1571220000000.0, 2506069000000.0, 2506070000000.0
1943993000000.0, 1943990000000.0, 2827612000000.0, 2827610000000.0
1950199000000.0, 1950200000000.0, 3185677000000.0, 3185680000000.0
Sierra Leone
[2010, 2011, 2012, 2013, 2014]
Guinea-Bissau
[]
346544218366.0, 346544000000.0, 1139352524771.0, 1139350000000.0
437922658380.0, 437923000000.0, 1074783801622.0, 1074780000000.0
487919960558.0, 487920000000.0, 932804001827.0, 932804000000.0
514220468560.0, 514221000000.0, 1006276606230.0, 1006280000000.0
Burundi
[2010, 2011, 2012, 2013]
Liberia
[]
2207100000000.0, 2207200000000.0, 2979800000000.0, 2979700000000.0
2306200000000.0, 2306300000000.0, 2960000000000.0, 2959900000000.0
Cameroon
[2014, 2015]
Madagascar
[]

Convert to Percent

In [30]:
for key in master_table: #iterate through master_table
  total_taxes = master_table[key].loc['Taxes']
  master_table[key] = master_table[key] / total_taxes * 100 #take all values as a fraction of total expenditure, then convert decimal to percent, then round to two decimal places

# master_table["Central African Republic"]

Calculate Yearly Averages

In [31]:
data_by_year_table = {
  2010: [],
  2011: [],
  2012: [],
  2013: [],
  2014: [],
  2015: [],
  2016: [],
  2017: [],
  2018: [],
  2019: [],
} #make table that stores data by year

# master_averages_ls = [] #make master averages list as place to store averages

for key in master_table:
  years_available = master_table[key].columns
  for year in data_by_year_table:
    if year in years_available:
      data_by_year_table[year].append(master_table[key][year])

yearly_averages_ls = [] #make a list of the yearly averages
for year in data_by_year_table:
  merged_year_df = pd.concat(data_by_year_table[year], axis=1, join='outer')
  year_average_df = merged_year_df.mean(axis=1) #get the average of all the countries' averages
  yearly_averages_ls.append(year_average_df)

 
# #Get average over decade
# #loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
# for key in master_table:
#   per_category_average = master_table[key].mean(axis=1) #get the average of each category (ignoring np.NaN values) into a list
#   # per_category_average.drop('To other government units', inplace=True) #drop 'To other government units' since there's two rows named that and will error
#   master_averages_ls.append(per_category_average) #add each country average to to the master averages list



# merged_averages_df = pd.concat(master_averages_ls, axis=1, join='outer')
# average__of_averages_df = merged_averages_df.mean(axis=1) #get the average of all the countries' averages
# average__of_averages_df

for i in range(len(yearly_averages_ls)):
  print(f"YEAR: {2010+i}")
  print(yearly_averages_ls[i])

YEAR: 2010
nan
Revenue                                                    162.023687
Taxes                                                           100.0
Taxes on income, profits, & capital gains                    24.91794
Taxes on income, profits, & capital gains: individuals      14.497633
Taxes on income, profits, & capital gains: corporations     10.192268
Taxes on income, profits, & capital gains: other             1.405851
Taxes on payroll & workforce                                 0.299997
Taxes on property                                            0.414927
Taxes on goods & services                                   46.523183
General taxes on goods & services                             35.0723
Excise taxes                                                   8.9861
Taxes on int trade & transactions                           20.278694
Other taxes n.e.c.                                           7.565258
Social contributions                                         1.666034
Social security contributions                                     0.0
Other social contributions                                   1.595765
Grants                                                      38.643355
Grants from foreign govts                                   22.323507
Grants from int orgs                                         19.04216
Grants from other gen govt                                        0.0
Grants from other gen govt: current                               0.0
Grants from other gen govt: capital                               0.0
Other revenue                                               21.922553
Property income                                              5.279415
Sales of goods & services                                    0.862964
Fines, penalties & forfeits                                  0.000572
Other transfers                                                5.3321
NI & SGS: premiums, fees & claims                                 0.0
dtype: object
YEAR: 2011
nan
Revenue                                                    214.898422
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   26.570962
Taxes on income, profits, & capital gains: individuals      14.253205
Taxes on income, profits, & capital gains: corporations     13.590037
Taxes on income, profits, & capital gains: other             1.060349
Taxes on payroll & workforce                                 0.285573
Taxes on property                                            0.457214
Taxes on goods & services                                   47.458435
General taxes on goods & services                           34.269139
Excise taxes                                                 8.434129
Taxes on int trade & transactions                           19.124381
Other taxes n.e.c.                                           6.103435
Social contributions                                         1.400782
Social security contributions                                     0.0
Other social contributions                                   1.316627
Grants                                                      37.071157
Grants from foreign govts                                   18.613393
Grants from int orgs                                        21.911528
Grants from other gen govt                                        0.0
Grants from other gen govt: current                               0.0
Grants from other gen govt: capital                               0.0
Other revenue                                               76.426483
Property income                                             55.298043
Sales of goods & services                                    1.345228
Fines, penalties & forfeits                                  0.038142
Other transfers                                              3.064327
NI & SGS: premiums, fees & claims                                 0.0
dtype: object
YEAR: 2012
nan
Revenue                                                    143.694715
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   25.439157
Taxes on income, profits, & capital gains: individuals      14.281114
Taxes on income, profits, & capital gains: corporations     12.991449
Taxes on income, profits, & capital gains: other             1.681681
Taxes on payroll & workforce                                 0.661292
Taxes on property                                            0.186897
Taxes on goods & services                                   54.292131
General taxes on goods & services                           40.426141
Excise taxes                                                11.531019
Taxes on int trade & transactions                           17.120264
Other taxes n.e.c.                                            2.30026
Social contributions                                         0.807906
Social security contributions                                     0.0
Other social contributions                                   0.623776
Grants                                                      25.759225
Grants from foreign govts                                    8.882742
Grants from int orgs                                        19.807099
Grants from other gen govt                                        0.0
Grants from other gen govt: current                               0.0
Grants from other gen govt: capital                               0.0
Other revenue                                               17.127585
Property income                                              8.364805
Sales of goods & services                                    2.560704
Fines, penalties & forfeits                                  0.336486
Other transfers                                              2.633109
NI & SGS: premiums, fees & claims                                 0.0
dtype: object
YEAR: 2013
nan
Revenue                                                    197.478896
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   30.936215
Taxes on income, profits, & capital gains: individuals      19.704268
Taxes on income, profits, & capital gains: corporations     15.995276
Taxes on income, profits, & capital gains: other              1.47269
Taxes on payroll & workforce                                  0.26097
Taxes on property                                             0.42771
Taxes on goods & services                                   45.558532
General taxes on goods & services                           30.688651
Excise taxes                                                 10.37236
Taxes on int trade & transactions                           21.368084
Other taxes n.e.c.                                           1.448489
Social contributions                                         0.749629
Social security contributions                                     0.0
Other social contributions                                   0.749629
Grants                                                      40.516274
Grants from foreign govts                                   10.188254
Grants from int orgs                                        35.676949
Grants from other gen govt                                        0.0
Grants from other gen govt: current                               0.0
Grants from other gen govt: capital                               0.0
Other revenue                                               56.212992
Property income                                             54.955127
Sales of goods & services                                    3.859561
Fines, penalties & forfeits                                  0.358246
Other transfers                                              0.729337
NI & SGS: premiums, fees & claims                            0.054477
dtype: object
YEAR: 2014
nan
Revenue                                                    157.596978
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   31.591552
Taxes on income, profits, & capital gains: individuals      14.978433
Taxes on income, profits, & capital gains: corporations     17.824822
Taxes on income, profits, & capital gains: other              2.19869
Taxes on payroll & workforce                                 0.375316
Taxes on property                                            0.519091
Taxes on goods & services                                   46.358539
General taxes on goods & services                           30.936039
Excise taxes                                                10.777385
Taxes on int trade & transactions                           18.587262
Other taxes n.e.c.                                           2.568239
Social contributions                                         0.726364
Social security contributions                                     0.0
Other social contributions                                   0.575437
Grants                                                      24.006825
Grants from foreign govts                                    4.232066
Grants from int orgs                                        21.420276
Grants from other gen govt                                   0.895874
Grants from other gen govt: current                          0.806392
Grants from other gen govt: capital                          0.089483
Other revenue                                               32.929822
Property income                                             27.852053
Sales of goods & services                                    3.177038
Fines, penalties & forfeits                                  0.440434
Other transfers                                               0.91348
NI & SGS: premiums, fees & claims                            0.006948
dtype: object
YEAR: 2015
nan
Revenue                                                    141.070584
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   31.133072
Taxes on income, profits, & capital gains: individuals      15.247189
Taxes on income, profits, & capital gains: corporations     17.674153
Taxes on income, profits, & capital gains: other             1.665804
Taxes on payroll & workforce                                 0.433608
Taxes on property                                            0.438789
Taxes on goods & services                                    47.19915
General taxes on goods & services                           32.984277
Excise taxes                                                  9.32794
Taxes on int trade & transactions                           18.823871
Other taxes n.e.c.                                           1.971511
Social contributions                                         0.739926
Social security contributions                                     0.0
Other social contributions                                   0.526894
Grants                                                      23.155561
Grants from foreign govts                                    5.668287
Grants from int orgs                                        20.107221
Grants from other gen govt                                   0.480241
Grants from other gen govt: current                          0.480241
Grants from other gen govt: capital                               0.0
Other revenue                                               17.242363
Property income                                             10.666135
Sales of goods & services                                    4.045116
Fines, penalties & forfeits                                  0.361099
Other transfers                                              1.230381
NI & SGS: premiums, fees & claims                            0.076952
dtype: object
YEAR: 2016
nan
Revenue                                                    140.805006
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   32.767742
Taxes on income, profits, & capital gains: individuals      18.832582
Taxes on income, profits, & capital gains: corporations      17.25346
Taxes on income, profits, & capital gains: other             0.806916
Taxes on payroll & workforce                                 0.418134
Taxes on property                                            0.402981
Taxes on goods & services                                   48.524264
General taxes on goods & services                           31.489756
Excise taxes                                                11.796402
Taxes on int trade & transactions                            15.74297
Other taxes n.e.c.                                           2.143909
Social contributions                                         0.684047
Social security contributions                                0.043994
Other social contributions                                   0.640053
Grants                                                       25.63465
Grants from foreign govts                                    3.564903
Grants from int orgs                                         27.41686
Grants from other gen govt                                   0.000868
Grants from other gen govt: current                          0.000868
Grants from other gen govt: capital                               0.0
Other revenue                                               14.554713
Property income                                             10.123361
Sales of goods & services                                    2.933013
Fines, penalties & forfeits                                  0.473667
Other transfers                                              0.409964
NI & SGS: premiums, fees & claims                            0.151288
dtype: object
YEAR: 2017
nan
Revenue                                                    140.934969
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   35.688804
Taxes on income, profits, & capital gains: individuals      16.430057
Taxes on income, profits, & capital gains: corporations     19.383024
Taxes on income, profits, & capital gains: other             1.134898
Taxes on payroll & workforce                                 0.775292
Taxes on property                                            0.442768
Taxes on goods & services                                   45.662631
General taxes on goods & services                           33.584531
Excise taxes                                                10.169262
Taxes on int trade & transactions                           15.483777
Other taxes n.e.c.                                           1.946728
Social contributions                                         0.774745
Social security contributions                                0.028193
Other social contributions                                   0.746552
Grants                                                      24.392555
Grants from foreign govts                                    4.737581
Grants from int orgs                                         21.70333
Grants from other gen govt                                   0.170736
Grants from other gen govt: current                          0.170736
Grants from other gen govt: capital                               0.0
Other revenue                                               15.845144
Property income                                             10.528564
Sales of goods & services                                    3.739349
Fines, penalties & forfeits                                  0.313426
Other transfers                                                0.2795
NI & SGS: premiums, fees & claims                            0.984304
dtype: object
YEAR: 2018
nan
Revenue                                                    159.652267
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   35.922002
Taxes on income, profits, & capital gains: individuals      16.699877
Taxes on income, profits, & capital gains: corporations     19.228154
Taxes on income, profits, & capital gains: other             1.372139
Taxes on payroll & workforce                                 0.785308
Taxes on property                                            0.270902
Taxes on goods & services                                   44.288221
General taxes on goods & services                           32.231369
Excise taxes                                                10.397524
Taxes on int trade & transactions                           16.928756
Other taxes n.e.c.                                            1.80481
Social contributions                                         1.336106
Social security contributions                                0.003981
Other social contributions                                   1.332125
Grants                                                      20.357958
Grants from foreign govts                                    1.906495
Grants from int orgs                                        18.451463
Grants from other gen govt                                        0.0
Grants from other gen govt: current                               0.0
Grants from other gen govt: capital                               0.0
Other revenue                                               38.106659
Property income                                             32.889464
Sales of goods & services                                    3.940379
Fines, penalties & forfeits                                  0.428581
Other transfers                                              0.837572
NI & SGS: premiums, fees & claims                            0.010663
dtype: object
YEAR: 2019
nan
Revenue                                                    154.258695
Taxes                                                           100.0
Taxes on income, profits, & capital gains                   37.227644
Taxes on income, profits, & capital gains: individuals      15.339156
Taxes on income, profits, & capital gains: corporations     22.039215
Taxes on income, profits, & capital gains: other             1.370139
Taxes on payroll & workforce                                 0.774766
Taxes on property                                            0.281627
Taxes on goods & services                                   46.562514
General taxes on goods & services                           35.591086
Excise taxes                                                 8.105056
Taxes on int trade & transactions                           13.724742
Other taxes n.e.c.                                           1.428707
Social contributions                                         0.840531
Social security contributions                                 0.01532
Other social contributions                                   0.825211
Grants                                                      16.897754
Grants from foreign govts                                    3.024937
Grants from int orgs                                        14.896238
Grants from other gen govt                                        0.0
Grants from other gen govt: current                               0.0
Grants from other gen govt: capital                               0.0
Other revenue                                               36.625476
Property income                                             33.096657
Sales of goods & services                                    2.820569
Fines, penalties & forfeits                                   0.44421
Other transfers                                              0.236619
NI & SGS: premiums, fees & claims                            0.027421
dtype: object

Calculate Percentages

In [32]:
# yearly_averages_percentage_ls = []
# for year_average_df in yearly_averages_ls:
#   total_taxes = year_average_df['Taxes']
#   year_average_percentage_df = year_average_df / total_taxes * 100 #take all values as a fraction of total expenditure, then convert decimal to percent, then round to two decimal places
#   yearly_averages_percentage_ls.append(year_average_percentage_df)

# for i in range(len(yearly_averages_percentage_ls)):
#   print(f"YEAR: {2010+i}")
#   print(yearly_averages_percentage_ls[i])

Calculate Average Across Period

In [33]:
merged_percentages_df = pd.concat(yearly_averages_ls, axis=1, join='outer')
average_df = merged_percentages_df.mean(axis=1)
rounded_average_df = average_df.apply(lambda x: round(x, 2))

rounded_average_df = rounded_average_df.to_frame()
rounded_average_df

                                                         0
nan
Revenue                                             161.24
Taxes                                               100.00
Taxes on income, profits, & capital gains            31.22
Taxes on income, profits, & capital gains: indi...   16.03
Taxes on income, profits, & capital gains: corp...   16.62
Taxes on income, profits, & capital gains: other      1.42
Taxes on payroll & workforce                          0.51
Taxes on property                                     0.38
Taxes on goods & services                            47.24
General taxes on goods & services                    33.73
Excise taxes                                          9.99
Taxes on int trade & transactions                    17.72
Other taxes n.e.c.                                    2.93
Social contributions                                  0.97
Social security contributions                         0.01
Other social contributions                            0.89
Grants                                               27.64
Grants from foreign govts                             8.31
Grants from int orgs                                 22.04
Grants from other gen govt                            0.15
Grants from other gen govt: current                   0.15
Grants from other gen govt: capital                   0.01
Other revenue                                        32.70
Property income                                      24.91
Sales of goods & services                             2.93
Fines, penalties & forfeits                           0.32
Other transfers                                       1.57
NI & SGS: premiums, fees & claims                     0.13

In [34]:
#check
first_level = 0
for category in first_level_ls:
  first_level += average_df[category]
print(first_level)

second_level = 0
for category in second_level_ls:
  second_level += average_df[category]
print(second_level)

161.31551744668326
100.00000000000001