Import Libraries

In [64]:
import pandas as pd
import numpy as np
import os
import yfinance as yf

Currency Codes

In [65]:
country_currency_codes_table = {
    'Burundi': 'BIF',
    'Benin': 'XOF',
    'Burkina Faso': 'XOF',
    'Central African Republic': 'XAF',
    "Côte d'Ivoire": 'XOF',
    'Cameroon': 'XAF',
    'Democratic Republic of the Congo': 'CDF',
    'Republic of Congo': 'XAF',
    'Comoros': 'KMF',
    'Eritrea': 'ERN',
    'Ethiopia': 'ETB',
    'Ghana': 'GHS',
    'Guinea': 'GNF',
    'The Gambia': 'GMD',
    'Guinea-Bissau': 'XOF',
    'Liberia': 'LRD',
    'Madagascar': 'MGA',
    'Mali': 'XOF',
    'Mozambique': 'MZN',
    'Mauritania': 'MRU',
    'Malawi': 'MWK',
    'Niger': 'XOF',
    'Rwanda': 'RWF',
    'Sudan': 'SDG',
    'Senegal': 'XOF',
    'Sierra Leone': 'SLL',
    'Somalia': 'SOS',
    'Sao Tomee and Principe': 'STN',
    'Chad': 'XAF',
    'Togo': 'XOF',
    'Tanzania': 'TZS',
    'Uganda': 'UGX',
    'Zambia': 'ZMW'
}

Read Data

In [66]:
#read in stata dataset as dataframe "country_code_df"
country_code_df = pd.read_stata("codesffactors_Mar23_2019.dta") 
country_code_df.replace('--', np.nan, inplace=True) #replace all entries that are '--' with NaN data value

country_code_df.head()

,countryname,wbctry,wbcode,wbregion,wbigroup2017,wblcat2017,hipc,emu,cemac,waemu,imfcode,imfweocode,imfweoiso,imfweoctry,region
0,Aruba,Aruba,ABW,Latin America & Caribbean,High income,NaN,0,0,0,0,NaN,314.0,ABW,Aruba,LAC
1,Afghanistan,Afghanistan,AFG,South Asia,Low income,IDA,1,0,0,0,512.0,512.0,AFG,Afghanistan,SAS
2,Angola,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD,0,0,0,0,614.0,614.0,AGO,Angola,SSA
3,Anguilla,NaN,AIA,Latin America & Caribbean,NaN,NaN,0,0,0,0,312.0,NaN,NaN,NaN,LAC
4,Albania,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD,0,0,0,0,914.0,914.0,ALB,Albania,ECA

In [67]:
region_classification_ls = country_code_df['wbregion'].unique() #get a list of region classifications
income_classification_ls = country_code_df['wbigroup2017'].unique() #get a list of income classifications
income_classification_ls = [x for x in income_classification_ls if not pd.isna(x)] # remove '--' from income_classification_ls

print(f"The region classifications are: {', '.join(country for country in region_classification_ls)}")
print(f"The income classifications are: {', '.join(country for country in income_classification_ls)}")

The region classifications are: Latin America & Caribbean, South Asia, Sub-Saharan Africa, Europe & Central Asia, Middle East & North Africa, East Asia & Pacific, North America
The income classifications are: High income, Low income, Lower middle income, Upper middle income

In [68]:
ssa_hipc_countries = country_code_df[(country_code_df['hipc'] == 1) & (country_code_df['wbregion'] == 'Sub-Saharan Africa')]
ssa_hipc_countries_ls = ssa_hipc_countries['imfweoctry'].to_list()

ssa_hipc_countries_ls

['Burundi',
 'Benin',
 'Burkina Faso',
 'Central African Republic',
 "Côte d'Ivoire",
 'Cameroon',
 'Democratic Republic of the Congo',
 'Republic of Congo',
 'Comoros',
 'Eritrea',
 'Ethiopia',
 'Ghana',
 'Guinea',
 'The Gambia',
 'Guinea-Bissau',
 'Liberia',
 'Madagascar',
 'Mali',
 'Mozambique',
 'Mauritania',
 'Malawi',
 'Niger',
 'Rwanda',
 'Sudan',
 'Senegal',
 'Sierra Leone',
 'Somalia',
 'São Tomé and Príncipe',
 'Chad',
 'Togo',
 'Tanzania',
 'Uganda',
 'Zambia']

Read in IMF's Government Finance Statistics

In [69]:
master_table = {}
folder_path = "revenue-data"

# Loop that goes through all files 'file_name' in the folder 'folder_path'
for file_name in os.listdir(folder_path):
  if file_name.endswith('.xlsx') and not file_name.startswith('~$'): #check to see if is spreadsheet .xlsx format
    raw_df = pd.read_excel(folder_path+ "/" + file_name) #read in .xlsx as dataframe
    master_table[file_name[:-5]] = raw_df #store dataframe as an entry in the master_table hash table

# master_table["Central African Republic"]
master_table["Benin"]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Detailed Revenue Breakdown,Detailed Revenue Breakdown,NaN,NaN,NaN
1,Country: Benin,NaN,NaN,NaN,NaN
2,Sector: Budgetary central government,NaN,NaN,NaN,NaN
3,Unit: Domestic currency,NaN,NaN,NaN,NaN
4,Scale: Billions,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,2010,2011.000000,2012.000000,2013.0
7,Revenue,648.375468,676.747224,701.455221,803.0
8,Taxes,536.250675,546.563646,599.904265,696.0
9,"Taxes on income, profits, & capital gains",104.846262,114.433242,118.073622,134.3
10,"Taxes on income, profits, & capital gains: ind...",46.00102,51.920867,56.326766,60.3
11,"Taxes on income, profits, & capital gains: cor...",47.753394,53.004216,53.119428,63.5
12,"Taxes on income, profits, & capital gains: other",11.091848,9.508159,8.627427,10.5
13,Taxes on payroll & workforce,5.104337,5.305594,5.726621,6.0
14,Taxes on property,1.681998,1.663647,1.280306,1.8
15,Taxes on goods & services,275.476543,282.885616,301.812744,349.9
16,General taxes on goods & services,232.742208,240.434099,269.594113,308.8
17,Excise taxes,23.150171,21.162270,8.915147,23.3
18,Taxes on int trade & transactions,142.732772,133.038373,163.913078,194.3
19,Other taxes n.e.c.,6.408763,9.237175,9.097894,9.7
20,Social contributions,16.366616,18.602945,20.718088,22.8
21,Social security contributions,16.366616,18.602945,20.718088,22.8
22,Other social contributions,0,0.000000,0.000000,0.0
23,Grants,52.312694,80.536882,46.590103,45.9
24,Grants from foreign govts,48.114343,76.823270,43.429216,40.9
25,Grants from int orgs,0,0.000000,0.000000,0.0
26,Grants from other gen govt,4.19835,3.713612,3.160887,5.0
27,Grants from other gen govt: current,4.19835,3.713612,3.160887,5.0
28,Grants from other gen govt: capital,0,0.000000,0.000000,0.0
29,Other revenue,43.445484,31.043751,34.242765,38.4
30,Property income,12.896126,10.423631,11.574620,9.0
31,Sales of goods & services,4.242073,4.135871,5.151810,8.0
32,"Fines, penalties & forfeits",1.156242,0.900713,0.878146,1.8
33,Other transfers,25.151043,15.583535,16.638189,NaN
34,"NI & SGS: premiums, fees & claims",0,0.000000,0.000000,NaN

Convert values to USD

In [70]:
error_countries = []

#loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
for key in master_table:
  scale = master_table[key].iloc[4,0] #get if values have scale of billions or millions
  
  # Drop rows 0 to 5, reformatting indexes and column headers
  master_table[key] = master_table[key].drop([0, 1, 2, 3, 4, 5]) 
  master_table[key] = master_table[key].reset_index(drop=True) 
  master_table[key].columns = master_table[key].iloc[0]
  master_table[key] = master_table[key][1:]
  master_table[key] = master_table[key].set_index(master_table[key].columns[0])

  if scale == "Scale: Billions":
    master_table[key] = master_table[key]* (10 ** 9) #multiple every value in dataframe by 1e9 if scale is billion
  elif scale == "Scale: Millions":
    master_table[key] = master_table[key]* (10 ** 6) #multiple every value in dataframe by 1e9 if scale is billion


  #get annual 2010-2019 USD to domestic currency exchange rate using yfinance library
  currency = country_currency_codes_table[key] #retrieve currency symbol from 'country_currency_codes_table'
  symbol = f"{currency}=X"
  try:
    data = yf.download(symbol, start="2010-01-01", end="2020-01-01", interval="1mo") #download monthly USD-Currency dataset from 2010-2020
    yearly_data_df = data['Close'].resample('YE').mean() #get the annual average exchange rate outputted as datafram
    yearly_data_table = yearly_data_df.to_dict() # Convert the yearly_data to a hash table with the date as the key
    year_to_exchange_rate_dict = {key.year: value for key, value in yearly_data_table.items()} # Convert the keys to only the year part
    print(year_to_exchange_rate_dict)

    #convert DataFrame values to USD
    for year in master_table[key].columns: #loop through columns in dataframe
      year_int = int(year)  # Convert year to integer to match the dictionary keys
      master_table[key][year] = master_table[key][year] / year_to_exchange_rate_dict[year_int] #divide each column's values by that year's exchange rate

  except Exception as e: #if errored out
    pass
    print(f"Could not fetch rate for {key} ({currency}): {e}")
    error_countries.append(key) #add country to error list
    

for country in error_countries:
  del master_table[country]
 
master_table["Benin"]

[*********************100%%**********************]  1 of 1 completed

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 487.5991668701172, 2011: 460.59083048502606, 2012: 501.04666900634766, 2013: 492.91916910807294, 2014: 497.4808349609375, 2015: 594.4341735839844, 2016: 594.0333353678385, 2017: 578.2424977620443, 2018: 556.1933390299479, 2019: 586.7139180501302}
{2010: 1526.5750020345051, 2011: 1574.0833333333333, 2012: 1587.1249898274739, 2013: 1351.7416585286458, 2014: 849.4726765950521, 2015: 593.25, 2016: 573.0257975260416, 2017: 557.7736612955729, 2018: 567.1666666666666, 2019: 570.6666666666666}
{2010: 1422.5833231608074, 2011: 1568.4333394368489, 2012: 1563.4083455403645, 2013: 1581.8916727701824, 2014: 1632.8416646321614, 2015: 1989.9833170572917, 2016: 2136.6749674479165, 2017: 2193.6416625976562, 2018: 2273.074991861979, 2019: 2301.0916748046875}
{2010: 886.25, 2011: 910.0, 2012: 904.5833333333334, 2013: 906.6291656494141, 2014: 907.25, 2015: 910.0, 2016: 978.4496866861979, 2017: 1457.9642842610676, 2018: 1580.0, 2019: 1630.0}
{2010: 575.0333302815756, 2011: 590.4300028483073, 2012: 599.2916666666666, 2013: 640.4175059000651, 2014: 674.0025024414062, 2015: 696.072499593099, 2016: 768.2083384195963, 2017: 827.0033365885416, 2018: 847.0541687011719, 2019: 901.6158345540365}
{2010: 487.5991668701172, 2011: 460.59083048502606, 2012: 501.04666900634766, 2013: 492.91916910807294, 2014: 497.4808349609375, 2015: 594.4341735839844, 2016: 594.0333353678385, 2017: 578.2424977620443, 2018: 556.1933390299479, 2019: 586.7139180501302}

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['STN=X']: YFInvalidPeriodError("%ticker%: Period 'max' is invalid, must be one of ['1d', '5d']")
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

{2010: 2.318599979082743, 2011: 2.648924986521403, 2012: 3.52014168103536, 2013: 4.590566674868266, 2014: 5.666366696357727, 2015: 5.987816691398621, 2016: 6.130283355712891, 2017: 6.609750032424927, 2018: 25.39816665649414, 2019: 45.693160692850746}
{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 148.9291674296061, 2011: 155.58916854858398, 2012: 247.6258316040039, 2013: 362.4624989827474, 2014: 410.5541687011719, 2015: 495.21583557128906, 2016: 700.3816680908203, 2017: 720.1374969482422, 2018: 704.3308308919271, 2019: 718.8183339436849}
Could not fetch rate for Sao Tomee and Principe (STN): Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'
{2010: 34.550000508626304, 2011: 28.579166730244953, 2012: 28.048333326975506, 2013: 29.664999802907307, 2014: 31.18499978383382, 2015: 39.24833265940348, 2016: 62.973334312438965, 2017: 62.673333168029785, 2018: 59.819166819254555, 2019: 61.90666675567627}
{2010: 3920.0, 2011: 4280.166666666667, 2012: 4277.166666666667, 2013: 4268.166666666667, 2014: 4302.333333333333, 2015: 4348.583333333333, 2016: 5087.916666666667, 2017: 7505.0, 2018: 7962.916666666667, 2019: 9048.333333333334}
{2010: 487.61083221435547, 2011: 460.5933329264323, 2012: 501.0466715494792, 2013: 492.91916910807294, 2014: 497.47583770751953, 2015: 594.4266713460287, 2016: 594.0358378092448, 2017: 577.82666015625, 2018: 557.75, 2019: 583.7949981689453}
{2010: 1206.0750122070312, 2011: 1216.6916605631511, 2012: 1396.4749857584636, 2013: 1531.5916748046875, 2014: 1530.9249877929688, 2015: 1536.9166666666667, 2016: 1605.7583312988281, 2017: 1700.5, 2018: 1756.2916666666667, 2019: 1822.7166646321614}
{2010: 70.31111145019531, 2011: 71.36666742960612, 2012: 72.72916730244954, 2013: 75.09500058492024, 2014: 80.8000005086263, 2015: 83.20833333333333, 2016: 89.58333333333333, 2017: 105.09583409627278, 2018: 144.7375005086263, 2019: 186.4666659037272}
{2010: 487.5991668701172, 2011: 460.59083048502606, 2012: 501.04666900634766, 2013: 492.91916910807294, 2014: 497.4808349609375, 2015: 594.4341735839844, 2016: 594.0333353678385, 2017: 578.2424977620443, 2018: 556.1933390299479, 2019: 586.7139180501302}
{2010: 2070.574991861979, 2011: 1995.8000183105469, 2012: 2154.4749755859375, 2013: 2174.9000040690103, 2014: 2460.4250284830728, 2015: 3095.6833699544272, 2016: 3135.3916625976562, 2017: 3076.9583333333335, 2018: 3307.1916707356772, 2019: 3290.9500080744424}

,2010,2011.0,2012.0,2013.0
nan,,,,
Revenue,1329698656.446114,1.469294e+09,1.399980e+09,1.629070e+09
Taxes,1099751357.831325,1.186651e+09,1.197302e+09,1.411996e+09
"Taxes on income, profits, & capital gains",215020370.76549,2.484475e+08,2.356539e+08,2.724585e+08
"Taxes on income, profits, & capital gains: individuals",94339618.19326,1.127260e+08,1.124182e+08,1.223324e+08
"Taxes on income, profits, & capital gains: corporations",97933415.952104,1.150781e+08,1.060169e+08,1.288244e+08
"Taxes on income, profits, & capital gains: other",22747336.620127,2.064328e+07,1.721881e+07,2.130167e+07
Taxes on payroll & workforce,10468055.387162,1.151904e+07,1.142932e+07,1.217238e+07
Taxes on property,3449468.155499,3.611964e+06,2.555262e+06,3.651714e+06
Taxes on goods & services,564951648.522647,6.141765e+08,6.023645e+08,7.098527e+08
General taxes on goods & services,477311398.204718,5.220095e+08,5.380619e+08,6.264719e+08
Excise taxes,47476736.974586,4.594567e+07,1.779305e+07,4.726941e+07
Taxes on int trade & transactions,292718623.474415,2.888413e+08,3.271413e+08,3.941823e+08
Other taxes n.e.c.,13143191.526112,2.005495e+07,1.815778e+07,1.967868e+07
Social contributions,33564914.843412,4.038909e+07,4.134962e+07,4.625505e+07
Social security contributions,33564914.843412,4.038909e+07,4.134962e+07,4.625505e+07
Other social contributions,0.0,0.000000e+00,0.000000e+00,0.000000e+00
Grants,107283699.042197,1.748546e+08,9.298556e+07,9.311872e+07
Grants from foreign govts,98673655.748174,1.667920e+08,8.667699e+07,8.297506e+07
Grants from int orgs,0.0,0.000000e+00,0.000000e+00,0.000000e+00
Grants from other gen govt,8610043.294023,8.062671e+06,6.308568e+06,1.014365e+07
Grants from other gen govt: current,8610043.294023,8.062671e+06,6.308568e+06,1.014365e+07
Grants from other gen govt: capital,0.0,0.000000e+00,0.000000e+00,0.000000e+00
Other revenue,89098684.72918,6.739948e+07,6.834247e+07,7.790324e+07
Property income,26447578.068427,2.263088e+07,2.310088e+07,1.825857e+07
Sales of goods & services,8699709.962832,8.979442e+06,1.028210e+07,1.622984e+07
"Fines, penalties & forfeits",2371240.371649,1.955550e+06,1.752623e+06,3.651714e+06
Other transfers,51580156.326272,3.383361e+07,3.320687e+07,NaN
"NI & SGS: premiums, fees & claims",0.0,0.000000e+00,0.000000e+00,NaN

Calculate Averages

In [71]:
master_averages_ls = [] #make master averages list as place to store averages

#Get average over decade
#loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
for key in master_table:
  per_category_average = master_table[key].mean(axis=1) #get the average of each category (ignoring np.NaN values) into a list
  # per_category_average.drop('To other government units', inplace=True) #drop 'To other government units' since there's two rows named that and will error
  master_averages_ls.append(per_category_average) #add each country average to to the master averages list


merged_averages_df = pd.concat(master_averages_ls, axis=1, join='outer')
average__of_averages_df = merged_averages_df.mean(axis=1) #get the average of all the countries' averages
average__of_averages_df

nan
Revenue                                                    2770386295.843223
Taxes                                                      1931828113.621924
Taxes on income, profits, & capital gains                   568208799.042841
Taxes on income, profits, & capital gains: individuals      263959205.442601
Taxes on income, profits, & capital gains: corporations     300242508.651176
Taxes on income, profits, & capital gains: other             34424751.124167
Taxes on payroll & workforce                                  8519820.731848
Taxes on property                                            12666863.764264
Taxes on goods & services                                   953822285.904208
General taxes on goods & services                           581043851.712063
Excise taxes                                                196296288.874653
Taxes on int trade & transactions                           347427057.357882
Other taxes n.e.c.                                           42188755.000921
Social contributions                                          12540467.24059
Social security contributions                                  2302786.56113
Other social contributions                                   10304056.730989
Grants                                                      354767781.412877
Grants from foreign govts                                   140044363.194923
Grants from int orgs                                        203368685.213757
Grants from other gen govt                                    2571403.836833
Grants from other gen govt: current                           1783226.442825
Grants from other gen govt: capital                            788177.394008
Other revenue                                               473921210.764999
Property income                                             247958894.274274
Sales of goods & services                                    75773878.551566
Fines, penalties & forfeits                                   7506630.115191
Other transfers                                              27556075.413677
NI & SGS: premiums, fees & claims                             2648496.304547
dtype: object

Calculate Percentages

In [72]:
total_taxes = average__of_averages_df['Taxes']
average__of_averages_df = round(average__of_averages_df / total_taxes * 100, 2) #take all values as a fraction of total expenditure, then convert decimal to percent, then round to two decimal places
average__of_averages_df

nan
Revenue                                                    143.407495
Taxes                                                           100.0
Taxes on income, profits, & capital gains                    29.41301
Taxes on income, profits, & capital gains: individuals        13.6637
Taxes on income, profits, & capital gains: corporations     15.541885
Taxes on income, profits, & capital gains: other             1.781978
Taxes on payroll & workforce                                 0.441024
Taxes on property                                            0.655693
Taxes on goods & services                                   49.374076
General taxes on goods & services                           30.077409
Excise taxes                                                10.161167
Taxes on int trade & transactions                           17.984367
Other taxes n.e.c.                                           2.183877
Social contributions                                          0.64915
Social security contributions                                0.119202
Other social contributions                                   0.533384
Grants                                                      18.364355
Grants from foreign govts                                    7.249318
Grants from int orgs                                        10.527266
Grants from other gen govt                                   0.133107
Grants from other gen govt: current                          0.092308
Grants from other gen govt: capital                            0.0408
Other revenue                                               24.532266
Property income                                             12.835453
Sales of goods & services                                    3.922392
Fines, penalties & forfeits                                  0.388577
Other transfers                                              1.426425
NI & SGS: premiums, fees & claims                            0.137098
dtype: object