Import Libraries

In [29]:
import pandas as pd
import numpy as np
import os
import yfinance as yf

Currency Codes

In [30]:
country_currency_codes_table = {
    'Burundi': 'BIF',
    'Benin': 'XOF',
    'Burkina Faso': 'XOF',
    'Central African Republic': 'XAF',
    "Côte d'Ivoire": 'XOF',
    'Cameroon': 'XAF',
    'Democratic Republic of the Congo': 'CDF',
    'Republic of Congo': 'XAF',
    'Comoros': 'KMF',
    'Eritrea': 'ERN',
    'Ethiopia': 'ETB',
    'Ghana': 'GHS',
    'Guinea': 'GNF',
    'The Gambia': 'GMD',
    'Guinea-Bissau': 'XOF',
    'Liberia': 'LRD',
    'Madagascar': 'MGA',
    'Mali': 'XOF',
    'Mozambique': 'MZN',
    'Mauritania': 'MRU',
    'Malawi': 'MWK',
    'Niger': 'XOF',
    'Rwanda': 'RWF',
    'Sudan': 'SDG',
    'Senegal': 'XOF',
    'Sierra Leone': 'SLL',
    'Somalia': 'SOS',
    'Sao Tomee and Principe': 'STN',
    'Chad': 'XAF',
    'Togo': 'XOF',
    'Tanzania': 'TZS',
    'Uganda': 'UGX',
    'Zambia': 'ZMW'
}

Read Data

In [31]:
#read in stata dataset as dataframe "country_code_df"
country_code_df = pd.read_stata("codesffactors_Mar23_2019.dta") 
country_code_df.replace('--', np.nan, inplace=True) #replace all entries that are '--' with NaN data value

country_code_df.head()

,countryname,wbctry,wbcode,wbregion,wbigroup2017,wblcat2017,hipc,emu,cemac,waemu,imfcode,imfweocode,imfweoiso,imfweoctry,region
0,Aruba,Aruba,ABW,Latin America & Caribbean,High income,NaN,0,0,0,0,NaN,314.0,ABW,Aruba,LAC
1,Afghanistan,Afghanistan,AFG,South Asia,Low income,IDA,1,0,0,0,512.0,512.0,AFG,Afghanistan,SAS
2,Angola,Angola,AGO,Sub-Saharan Africa,Lower middle income,IBRD,0,0,0,0,614.0,614.0,AGO,Angola,SSA
3,Anguilla,NaN,AIA,Latin America & Caribbean,NaN,NaN,0,0,0,0,312.0,NaN,NaN,NaN,LAC
4,Albania,Albania,ALB,Europe & Central Asia,Upper middle income,IBRD,0,0,0,0,914.0,914.0,ALB,Albania,ECA

In [32]:
region_classification_ls = country_code_df['wbregion'].unique() #get a list of region classifications
income_classification_ls = country_code_df['wbigroup2017'].unique() #get a list of income classifications
income_classification_ls = [x for x in income_classification_ls if not pd.isna(x)] # remove '--' from income_classification_ls

print(f"The region classifications are: {', '.join(country for country in region_classification_ls)}")
print(f"The income classifications are: {', '.join(country for country in income_classification_ls)}")

The region classifications are: Latin America & Caribbean, South Asia, Sub-Saharan Africa, Europe & Central Asia, Middle East & North Africa, East Asia & Pacific, North America
The income classifications are: High income, Low income, Lower middle income, Upper middle income

In [33]:
ssa_hipc_countries = country_code_df[(country_code_df['hipc'] == 1) & (country_code_df['wbregion'] == 'Sub-Saharan Africa')]
ssa_hipc_countries_ls = ssa_hipc_countries['imfweoctry'].to_list()

ssa_hipc_countries_ls

['Burundi',
 'Benin',
 'Burkina Faso',
 'Central African Republic',
 "Côte d'Ivoire",
 'Cameroon',
 'Democratic Republic of the Congo',
 'Republic of Congo',
 'Comoros',
 'Eritrea',
 'Ethiopia',
 'Ghana',
 'Guinea',
 'The Gambia',
 'Guinea-Bissau',
 'Liberia',
 'Madagascar',
 'Mali',
 'Mozambique',
 'Mauritania',
 'Malawi',
 'Niger',
 'Rwanda',
 'Sudan',
 'Senegal',
 'Sierra Leone',
 'Somalia',
 'São Tomé and Príncipe',
 'Chad',
 'Togo',
 'Tanzania',
 'Uganda',
 'Zambia']

Read in IMF's Government Finance Statistics

In [34]:
master_table = {}
folder_path = "expenditure-data"

# Loop that goes through all files 'file_name' in the folder 'folder_path'
for file_name in os.listdir(folder_path):
  if file_name.endswith('.xlsx') and not file_name.startswith('~$'): #check to see if is spreadsheet .xlsx format
    raw_df = pd.read_excel(folder_path+ "/" + file_name) #read in .xlsx as dataframe
    master_table[file_name[:-5]] = raw_df #store dataframe as an entry in the master_table hash table

# master_table["Central African Republic"]
master_table["Benin"]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,Detailed Expense Breakdown,NaN,NaN,NaN,NaN
1,Country: Benin,NaN,NaN,NaN,NaN
2,Sector: Budgetary central government,NaN,NaN,NaN,NaN
3,Unit: Domestic currency,NaN,NaN,NaN,NaN
4,Scale: Billions,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN
6,NaN,2010.000000,2011.000000,2012.000000,2013.0
7,Expense,459.011490,457.660567,534.669798,577.5
8,Compensation of employees,235.600075,242.117067,267.900275,296.2
9,Wages and salaries,235.600075,242.117067,267.900275,296.2
10,Employers' social contributions,0.000000,0.000000,0.000000,0.0
11,Use of goods and services,71.197566,68.703453,94.436470,106.1
12,Interest expense,17.734935,14.973871,23.143175,19.9
13,To nonresidents,8.106149,7.831106,10.604660,9.8
14,To residents other than government units,9.628786,7.142766,12.538515,10.1
15,To other government units,0.000000,0.000000,0.000000,0.0
16,Subsidies,20.525565,33.553247,55.091217,49.5
17,To public corporations,20.525565,33.553247,55.091217,49.5
18,To private enterprises,0.000000,0.000000,0.000000,0.0
19,To other sectors,0.000000,0.000000,0.000000,0.0
20,Grants,101.794146,86.975987,80.503177,91.1
21,To foreign governments,0.000000,0.000000,0.000000,0.0
22,To international organizations,6.166268,5.812560,6.894267,8.2
23,To other government units,95.627878,81.163427,73.608910,82.9
24,Current,95.627878,81.163427,73.608910,82.9
25,Capital,0.000000,0.000000,0.000000,0.0
26,Social benefits,0.775000,0.987000,0.783000,0.9
27,Social security benefits,0.000000,0.000000,0.000000,0.0
28,Social assistance benefits,0.000000,0.000000,0.000000,0.0
29,Employment-related social benefits,0.775000,0.987000,0.783000,0.9
30,Other expense,11.384204,10.349942,12.812484,13.7
31,Property expense other than interest,0.000000,0.000000,0.000000,0.0
32,Expense on other transfers,11.384204,10.349942,12.812484,13.7

Convert values to USD

In [35]:
#REMOVE "JUNK" ROWS AND CONVERT TO CORRECT SCALE (MILLION/BILLIONS)
for key in master_table: #loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
  scale = master_table[key].iloc[4,0] #get if values have scale of billions or millions
  
  # Drop rows 0 to 5, reformatting indexes and column headers
  master_table[key] = master_table[key].drop([0, 1, 2, 3, 4, 5]) 
  master_table[key] = master_table[key].reset_index(drop=True) 
  master_table[key].columns = master_table[key].iloc[0]
  master_table[key] = master_table[key][1:]
  master_table[key] = master_table[key].set_index(master_table[key].columns[0])
  master_table[key].columns = [int(float(col)) for col in master_table[key].columns]
  # master_table[key] = master_table[key].fillna(0)

  if scale == "Scale: Billions":
    master_table[key] = master_table[key]* (10 ** 9) #multiple every value in dataframe by 1e9 if scale is billion
  elif scale == "Scale: Millions":
    master_table[key] = master_table[key]* (10 ** 6) #multiple every value in dataframe by 1e9 if scale is billion


#FILTER OUT COUNTRIES WITH LESS THAN 7 YEARS OF DATA
less_than_seven_years_data_countries = [] #create list to store countries with less than 7 years of historial data
for key in master_table: #iterate through master_table
  num_columns = master_table[key].shape[1] #count the number of columns (each column represents a year)
  if num_columns < 7: #if less than 7 columns/year, add to list to delete
    less_than_seven_years_data_countries.append(key)

for country in less_than_seven_years_data_countries:
  del master_table[country] #delete countries with less than 7 years from data table



# #CONVERT LOCAL CURRENCY DENOMINATED VALUES TO USD
# error_countries = []
# for key in master_table:
#   #get annual 2010-2019 USD to domestic currency exchange rate using yfinance library
#   currency = country_currency_codes_table[key] #retrieve currency symbol from 'country_currency_codes_table'
#   symbol = f"{currency}=X"
#   try:
#     data = yf.download(symbol, start="2010-01-01", end="2020-01-01", interval="1mo") #download monthly USD-Currency dataset from 2010-2020
#     yearly_data_df = data['Close'].resample('YE').mean() #get the annual average exchange rate outputted as datafram
#     yearly_data_table = yearly_data_df.to_dict() # Convert the yearly_data to a hash table with the date as the key
#     year_to_exchange_rate_dict = {key.year: value for key, value in yearly_data_table.items()} # Convert the keys to only the year part
#     print(year_to_exchange_rate_dict)

#     #convert DataFrame values to USD
#     for year in master_table[key].columns: #loop through columns in dataframe
#       year_int = int(year)  # Convert year to integer to match the dictionary keys
#       master_table[key][year] = master_table[key][year] / year_to_exchange_rate_dict[year_int] #divide each column's values by that year's exchange rate

#   except Exception as e: #if errored out
#     print(f"Could not fetch rate for {key} ({currency}): {e}")
#     error_countries.append(key) #add country to error list
#     pass
    
# for country in error_countries:
#   del master_table[country] #delete countries where currency conversion failed
 
master_table["Central African Republic"]

,2010,2011,2012,2014,2015,2016,2017,2018,2019
nan,,,,,,,,,
Expense,1.731918e+11,1.546884e+11,1.048890e+11,7.739077e+10,9.330681e+10,9.756730e+10,1.044100e+11,1.248852e+11,1.293590e+11
Compensation of employees,4.281015e+10,4.599096e+10,5.121265e+10,5.378400e+10,5.667560e+10,4.918200e+10,5.000300e+10,6.133600e+10,6.505200e+10
Wages and salaries,4.098525e+10,4.400347e+10,4.901595e+10,5.146438e+10,5.414420e+10,4.734605e+10,4.773844e+10,5.888674e+10,5.708700e+10
Employers' social contributions,1.824898e+09,1.987488e+09,2.196698e+09,2.319623e+09,2.531400e+09,1.835951e+09,2.264559e+09,2.449258e+09,7.965000e+09
Use of goods and services,1.002878e+11,7.543288e+10,2.499334e+10,6.348000e+09,1.523364e+10,2.197200e+10,2.774400e+10,3.047800e+10,3.637100e+10
Interest expense,9.511550e+09,6.983069e+09,5.923666e+09,2.169769e+09,4.697813e+09,1.155630e+09,2.205000e+09,2.801230e+09,6.482000e+09
To nonresidents,2.779550e+09,2.709069e+09,2.363420e+09,2.032978e+09,3.345018e+08,1.085000e+09,2.091000e+09,2.656230e+09,1.642000e+09
To residents other than government units,6.732000e+09,4.274000e+09,3.560247e+09,1.367905e+08,4.363311e+09,7.063000e+07,1.140000e+08,1.450000e+08,0.000000e+00
To other government units,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.840000e+09
Subsidies,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
To public corporations,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
To private enterprises,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
To other sectors,NaN,NaN,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Grants,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
To foreign governments,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
To international organizations,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
To other government units,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Current,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Capital,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Social benefits,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Social security benefits,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Social assistance benefits,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Employment-related social benefits,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Other expense,4.000000e+08,3.000000e+09,NaN,1.508900e+10,1.669976e+10,2.525767e+10,2.445800e+10,3.027000e+10,2.145400e+10
Property expense other than interest,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
Expense on other transfers,4.000000e+08,3.000000e+09,NaN,1.508900e+10,1.669976e+10,2.525767e+10,2.445800e+10,3.027000e+10,2.145400e+10

Convert to Percent

In [36]:
for key in master_table: #iterate through master_table
  total_expense = master_table[key].loc['Expense']
  master_table[key] = master_table[key] / total_expense * 100 #take all values as a fraction of total expenditure, then convert decimal to percent, then round to two decimal places

master_table["Central African Republic"]

,2010,2011,2012,2014,2015,2016,2017,2018,2019
nan,,,,,,,,,
Expense,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
Compensation of employees,24.718338,29.731357,48.825564,69.496661,60.741120,50.408285,47.891007,49.113894,50.287958
Wages and salaries,23.664652,28.446524,46.731256,66.499375,58.028135,48.526557,45.722096,47.152687,44.130675
Employers' social contributions,1.053686,1.284834,2.094308,2.997286,2.712985,1.881728,2.168910,1.961207,6.157283
Use of goods and services,57.905588,48.764408,23.828373,8.202529,16.326395,22.519841,26.572167,24.404808,28.116327
Interest expense,5.491916,4.514281,5.647557,2.803653,5.034801,1.184444,2.111867,2.243043,5.010861
To nonresidents,1.604897,1.751308,2.253258,2.626900,0.358497,1.112053,2.002682,2.126937,1.269336
To residents other than government units,3.887019,2.762974,3.394299,0.176753,4.676305,0.072391,0.109185,0.116107,0.000000
To other government units,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.741526
Subsidies,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
To public corporations,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
To private enterprises,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
To other sectors,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Grants,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
To foreign governments,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
To international organizations,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
To other government units,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Current,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Capital,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Social benefits,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Social security benefits,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Social assistance benefits,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Employment-related social benefits,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Other expense,0.230958,1.939383,NaN,19.497157,17.897684,25.887430,23.424959,24.238255,16.584853
Property expense other than interest,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Expense on other transfers,0.230958,1.939383,NaN,19.497157,17.897684,25.887430,23.424959,24.238255,16.584853

Calculate Yearly Averages

In [37]:
data_by_year_table = {
  2010: [],
  2011: [],
  2012: [],
  2013: [],
  2014: [],
  2015: [],
  2016: [],
  2017: [],
  2018: [],
  2019: [],
} #make table that stores data by year

# master_averages_ls = [] #make master averages list as place to store averages

for key in master_table:
  years_available = master_table[key].columns
  for year in data_by_year_table:
    if year in years_available:
      data = master_table[key][year]
      data.drop('To other government units', inplace=True)
      data_by_year_table[year].append(data)


yearly_averages_ls = [] #make a list of the yearly averages
for year in data_by_year_table:
  merged_year_df = pd.concat(data_by_year_table[year], axis=1, join='outer')
  year_average_df = merged_year_df.mean(axis=1) #get the average of all the countries' averages
  yearly_averages_ls.append(year_average_df)

 
# #Get average over decade
# #loop through table (where key is the country name) (master_table[key] is the dataframe stored in the master_table indexed by key)
# for key in master_table:
#   per_category_average = master_table[key].mean(axis=1) #get the average of each category (ignoring np.NaN values) into a list
#   # per_category_average.drop('To other government units', inplace=True) #drop 'To other government units' since there's two rows named that and will error
#   master_averages_ls.append(per_category_average) #add each country average to to the master averages list



# merged_averages_df = pd.concat(master_averages_ls, axis=1, join='outer')
# average__of_averages_df = merged_averages_df.mean(axis=1) #get the average of all the countries' averages
# average__of_averages_df

for i in range(len(yearly_averages_ls)):
  print(f"YEAR: {2010+i}")
  print(yearly_averages_ls[i])

YEAR: 2010
nan
Expense                                     100.000000
Compensation of employees                    34.865685
Wages and salaries                           31.541157
Employers' social contributions               1.520964
Use of goods and services                    25.932302
Interest expense                              6.469680
To nonresidents                               1.913966
To residents other than government units      4.164547
Subsidies                                     7.193627
To public corporations                        5.991368
To private enterprises                        1.391076
To other sectors                              0.000000
Grants                                       18.084170
To foreign governments                        0.054208
To international organizations                0.836049
Current                                      16.515672
Capital                                       1.595776
Social benefits                               2.373594
Social security benefits                      0.218075
Social assistance benefits                    0.633681
Employment-related social benefits            1.659605
Other expense                                 5.157873
Property expense other than interest          0.000022
Expense on other transfers                    5.150038
Consumption of fixed capital                       NaN
dtype: float64
YEAR: 2011
nan
Expense                                     100.000000
Compensation of employees                    35.256357
Wages and salaries                           31.302136
Employers' social contributions               1.826517
Use of goods and services                    26.198994
Interest expense                              6.572185
To nonresidents                               1.959999
To residents other than government units      4.022655
Subsidies                                     6.083806
To public corporations                        4.851832
To private enterprises                        1.203050
To other sectors                              0.000000
Grants                                       18.506004
To foreign governments                        0.029572
To international organizations                0.310426
Current                                      17.196914
Capital                                       1.852307
Social benefits                               2.452996
Social security benefits                      0.209460
Social assistance benefits                    0.584437
Employment-related social benefits            1.794049
Other expense                                 4.718808
Property expense other than interest          0.000068
Expense on other transfers                    4.985112
Consumption of fixed capital                       NaN
dtype: float64
YEAR: 2012
nan
Expense                                     100.000000
Compensation of employees                    37.527602
Wages and salaries                           33.881574
Employers' social contributions               2.182064
Use of goods and services                    22.550649
Interest expense                              6.455665
To nonresidents                               1.896822
To residents other than government units      4.022335
Subsidies                                     3.731190
To public corporations                        1.634896
To private enterprises                        1.218442
To other sectors                              0.385128
Grants                                       19.792213
To foreign governments                        0.000000
To international organizations                0.232353
Current                                      16.420274
Capital                                       3.127859
Social benefits                               1.952972
Social security benefits                      0.000005
Social assistance benefits                    0.323239
Employment-related social benefits            1.738537
Other expense                                 7.490723
Property expense other than interest          0.000025
Expense on other transfers                    7.484110
Consumption of fixed capital                       NaN
dtype: float64
YEAR: 2013
nan
Expense                                     100.000000
Compensation of employees                    37.024199
Wages and salaries                           33.209494
Employers' social contributions               2.673689
Use of goods and services                    21.812510
Interest expense                              7.524890
To nonresidents                               1.787728
To residents other than government units      5.037440
Subsidies                                     4.172585
To public corporations                        1.664010
To private enterprises                        2.186046
To other sectors                              0.157610
Grants                                       22.026030
To foreign governments                        0.000000
To international organizations                0.421396
Current                                      18.739427
Capital                                       2.879537
Social benefits                               1.596956
Social security benefits                      0.000001
Social assistance benefits                    0.359246
Employment-related social benefits            1.330099
Other expense                                 6.146431
Property expense other than interest          0.000000
Expense on other transfers                    6.065673
Consumption of fixed capital                       NaN
dtype: float64
YEAR: 2014
nan
Expense                                     100.000000
Compensation of employees                    37.788764
Wages and salaries                           32.736852
Employers' social contributions               2.080955
Use of goods and services                    21.267143
Interest expense                              7.785812
To nonresidents                               1.836068
To residents other than government units      4.413033
Subsidies                                     2.782260
To public corporations                        0.744754
To private enterprises                        1.421718
To other sectors                              0.404490
Grants                                       21.234983
To foreign governments                        0.000000
To international organizations                0.246708
Current                                      17.301555
Capital                                       3.686720
Social benefits                               1.803584
Social security benefits                      0.017921
Social assistance benefits                    0.517012
Employment-related social benefits            1.246841
Other expense                                 7.492034
Property expense other than interest          0.000000
Expense on other transfers                    7.481480
dtype: float64
YEAR: 2015
nan
Expense                                     100.000000
Compensation of employees                    36.638727
Wages and salaries                           32.157406
Employers' social contributions               2.069602
Use of goods and services                    20.590043
Interest expense                              8.531772
To nonresidents                               2.341235
To residents other than government units      4.700009
Subsidies                                     3.171851
To public corporations                        1.561820
To private enterprises                        1.234653
To other sectors                              0.354438
Grants                                       23.074624
To foreign governments                        0.000284
To international organizations                0.835473
Current                                      18.414131
Capital                                       3.824736
Social benefits                               1.901345
Social security benefits                      0.000022
Social assistance benefits                    0.581419
Employment-related social benefits            1.411468
Other expense                                 6.267852
Property expense other than interest          0.000000
Expense on other transfers                    6.246793
dtype: float64
YEAR: 2016
nan
Expense                                     100.000000
Compensation of employees                    37.290144
Wages and salaries                           33.523940
Employers' social contributions               2.014850
Use of goods and services                    21.238495
Interest expense                              9.501130
To nonresidents                               2.697685
To residents other than government units      6.576672
Subsidies                                     3.519113
To public corporations                        1.808716
To private enterprises                        1.380285
To other sectors                              0.312738
Grants                                       20.423556
To foreign governments                        0.023477
To international organizations                0.814312
Current                                      15.483098
Capital                                       4.102668
Social benefits                               2.236625
Social security benefits                      0.000027
Social assistance benefits                    0.450807
Employment-related social benefits            1.785790
Other expense                                 5.974708
Property expense other than interest          0.000000
Expense on other transfers                    5.953095
dtype: float64
YEAR: 2017
nan
Expense                                     100.000000
Compensation of employees                    36.156733
Wages and salaries                           34.346020
Employers' social contributions               1.788345
Use of goods and services                    20.765296
Interest expense                             10.557224
To nonresidents                               2.956241
To residents other than government units      7.297289
Subsidies                                     3.118798
To public corporations                        1.598797
To private enterprises                        0.985131
To other sectors                              0.506718
Grants                                       20.268499
To foreign governments                        0.000000
To international organizations                0.806617
Current                                      15.089803
Capital                                       4.372080
Social benefits                               2.387235
Social security benefits                      0.000014
Social assistance benefits                    0.683726
Employment-related social benefits            1.703495
Other expense                                 6.910364
Property expense other than interest          0.000000
Expense on other transfers                    6.882853
dtype: float64
YEAR: 2018
nan
Expense                                     100.000000
Compensation of employees                    35.972244
Wages and salaries                           34.174555
Employers' social contributions               1.630662
Use of goods and services                    20.901208
Interest expense                             11.906785
To nonresidents                               3.216476
To residents other than government units      6.353985
Subsidies                                     2.839203
To public corporations                        1.300115
To private enterprises                        0.848194
To other sectors                              0.652511
Grants                                       18.737744
To foreign governments                        0.000000
To international organizations                0.209136
Current                                      15.053944
Capital                                       2.988737
Social benefits                               2.508734
Social security benefits                      0.000024
Social assistance benefits                    0.772969
Employment-related social benefits            1.825600
Other expense                                 7.291815
Property expense other than interest          0.000000
Expense on other transfers                    7.262362
dtype: float64
YEAR: 2019
nan
Expense                                     100.000000
Compensation of employees                    36.840117
Wages and salaries                           35.348561
Employers' social contributions               1.789151
Use of goods and services                    20.022339
Interest expense                             12.754722
To nonresidents                               3.341982
To residents other than government units      7.655899
Subsidies                                     4.051069
To public corporations                        1.536622
To private enterprises                        2.029809
To other sectors                              0.429559
Grants                                       17.698164
To foreign governments                        0.000000
To international organizations                0.300975
Current                                      13.546013
Capital                                       3.851499
Social benefits                               2.649944
Social security benefits                      0.000000
Social assistance benefits                    0.760021
Employment-related social benefits            1.889923
Other expense                                 6.236838
Property expense other than interest          0.000000
Expense on other transfers                    6.226759
dtype: float64

Calculate Average Across Period

In [38]:
merged_percentages_df = pd.concat(yearly_averages_ls, axis=1, join='outer')
average_df = merged_percentages_df.mean(axis=1)
rounded_average_df = average_df.apply(lambda x: round(x, 2))

rounded_average_df = rounded_average_df.to_frame()
rounded_average_df

                                               0
nan
Expense                                   100.00
Compensation of employees                  36.54
Wages and salaries                         33.22
Employers' social contributions             1.96
Use of goods and services                  22.13
Interest expense                            8.81
To nonresidents                             2.39
To residents other than government units    5.42
Subsidies                                   4.07
To public corporations                      2.27
To private enterprises                      1.39
To other sectors                            0.32
Grants                                     19.98
To foreign governments                      0.01
To international organizations              0.50
Current                                    16.38
Capital                                     3.23
Social benefits                             2.19
Social security benefits                    0.04
Social assistance benefits                  0.57
Employment-related social benefits          1.64
Other expense                               6.37
Property expense other than interest        0.00
Expense on other transfers                  6.37
Consumption of fixed capital                 NaN

In [39]:
#one method filter for countries with 7+ years of data, aggregate in way that preserves identities
#unweighted - convert to share and take average (ratios period by period and then average)